// AUTO-GENERATED by scripts/build-viz-variants.mjs — do not edit.
// Run `npm run viz:variants` after upgrading edododraw.
//
// 82 of edododraw's 87 visualization templates, each with the curated
// runnable demo the package ships for it. The 5 missing ones —
// personas, vision, hole, tug-of-war, quote — draw character figures, which are
// known-broken upstream and are not used anywhere in this library.
//
// Categories: Brainstorming · Business Frameworks · Cause and Effect · Comparison · Data · Parts of a whole · Problems and Solutions · Process · Timelines · Visual Metaphors
import type {EffectMeta} from '../../../types';

export const VIZ_VARIANTS: NonNullable<EffectMeta['variants']> = [
  {
    id: 'clouds',
    name: 'Clouds',
    tagline: 'Scattered thought-cloud islands — a loose collection of ideas.',
    props: {vizType: 'clouds', vizCategory: 'Brainstorming', source: `viz clouds "What We Heard" {
  item "Onboarding is confusing" { icon: warning }
  item "Docs are loved" { icon: heart }
  item "Pricing feels fair" { icon: dollar }
  item "Mobile is missed" { icon: phone }
  item "Support is fast" { icon: rocket }
}`},
  },
  {
    id: 'head-thoughts',
    name: 'Head thoughts',
    tagline: 'A profile-head container — what\'s going on in someone\'s mind.',
    props: {vizType: 'head-thoughts', vizCategory: 'Brainstorming', source: `viz head-thoughts "Inside the Customer's Head" {
  who: "Your customer"
  item "Will this save me time?" { icon: clock }
  item "Can I trust it?" { icon: shield }
  item "What does it cost?" { icon: dollar }
  item "Is it easy to leave?" { icon: key }
}`},
  },
  {
    id: 'key-ideas',
    name: 'Key ideas',
    tagline: 'A row of lightbulbs, one per idea.',
    props: {vizType: 'key-ideas', vizCategory: 'Brainstorming', source: `viz key-ideas "Retreat Themes" {
  item "Focus" "Fewer projects, finished properly"
  item "Craft" "Raise the quality bar everywhere"
  item "Speed" "Ship weekly, learn faster"
}`},
  },
  {
    id: 'list',
    name: 'List',
    tagline: 'A styled list; vertical up to 5 items, horizontal from 6.',
    props: {vizType: 'list', vizCategory: 'Brainstorming', source: `viz list "Core Values" {
  item "Ship it" "Progress over polish theater" { icon: rocket }
  item "Own it" "No one else is coming" { icon: user }
  item "Say it" "Direct, kind feedback" { icon: chat }
  item "Learn it" "Curiosity as default" { icon: book }
}`},
  },
  {
    id: 'mindmap',
    name: 'Mindmap',
    tagline: 'A central topic branching in both directions; variants: -left, -right, -horizontal, -vertical.',
    props: {vizType: 'mindmap', vizCategory: 'Brainstorming', source: `viz mindmap "Product Launch" {
  item "Marketing" { item "Landing page"; item "Email campaign"; item "Social posts" }
  item "Engineering" { item "Feature freeze"; item "Load testing" }
  item "Sales" { item "Demo script"; item "Pricing sheet" }
  item "Support" { item "Help articles"; item "Escalation plan" }
  item "Legal" { item "Terms update" }
}`},
  },
  {
    id: 'mindmap-horizontal',
    name: 'Mindmap — horizontal',
    tagline: 'Root at the left, branches one column right, children a column beyond — a site map or tree.',
    props: {vizType: 'mindmap-horizontal', vizCategory: 'Brainstorming', source: `viz mindmap-horizontal "Docs Site Map" {
  item "Getting started" { item "Install"; item "First diagram" }
  item "Language" { item "Nodes & edges"; item "Styles"; item "Visualizations" }
  item "Guides" { item "Camera & timeline"; item "Annotations" }
  item "Reference" { item "API"; item "Style presets" }
}`},
  },
  {
    id: 'mindmap-left',
    name: 'Mindmap — left',
    tagline: 'Every branch fans to the left of the root; reads as inputs feeding in.',
    props: {vizType: 'mindmap-left', vizCategory: 'Brainstorming', source: `viz mindmap-left "Where Bugs Come From" {
  item "Unclear specs" { item "Unwritten assumptions"; item "Late scope changes" }
  item "Thin tests" { item "Untested edge cases"; item "Flaky CI" }
  item "Rushed reviews" { item "Diffs too big"; item "No context" }
}`},
  },
  {
    id: 'mindmap-right',
    name: 'Mindmap — right',
    tagline: 'Every branch fans to the right of the root; reads as a plan unrolling.',
    props: {vizType: 'mindmap-right', vizCategory: 'Brainstorming', source: `viz mindmap-right "Onboarding Plan" {
  item "Week 1" { item "Laptop + accounts"; item "Meet the team"; item "Ship a typo fix" }
  item "Month 1" { item "Own a small feature"; item "Shadow on-call" }
  item "Quarter 1" { item "Lead a project"; item "Mentor the next hire" }
}`},
  },
  {
    id: 'mindmap-vertical',
    name: 'Mindmap — vertical',
    tagline: 'Org-chart mindmap: root centered, branch cards above and below on elbow trunks.',
    props: {vizType: 'mindmap-vertical', vizCategory: 'Brainstorming', source: `viz mindmap-vertical "Engineering Org" {
  item "Platform" { item "Runtime"; item "Data" }
  item "Product" { item "Web"; item "Mobile" }
  item "Quality" { item "Test infra"; item "Release" }
}`},
  },
  {
    id: 'bullseye',
    name: 'Bullseye',
    tagline: 'Concentric priority rings, outermost first.',
    props: {vizType: 'bullseye', vizCategory: 'Business Frameworks', source: `viz bullseye "Target Market" {
  item "Addressable market" "Everyone who could buy" { icon: globe }
  item "Serviceable market" "Who we can reach today" { icon: target }
  item "Beachhead" "Design-led B2B startups" { icon: flag }
}`},
  },
  {
    id: 'business-model-canvas',
    name: 'Business Model Canvas',
    tagline: 'The classic 9-box BMC grid with bullet sections.',
    props: {vizType: 'business-model-canvas', vizCategory: 'Business Frameworks', source: `viz business-model-canvas "EDodo, Inc." {
  partners { item "Cloud provider"; item "Design agencies" }
  activities { item "Engine development"; item "Community" }
  resources { item "Rendering engine"; item "Template library" }
  value { item "Diagrams from plain text"; item "Hand-drawn warmth" }
  relationships { item "Self-serve"; item "Discord community" }
  channels { item "npm + docs site"; item "Conference talks" }
  segments { item "Dev-tool teams"; item "Educators" }
  costs { item "R&D"; item "Infrastructure" }
  revenue { item "Pro licenses"; item "Support plans" }
}`},
  },
  {
    id: 'ecosystem',
    name: 'Ecosystem',
    tagline: 'Concentric stakeholder orbits around one center.',
    props: {vizType: 'ecosystem', vizCategory: 'Business Frameworks', source: `viz ecosystem "Platform" {
  center "EDodo Core" { icon: gear }
  ring "Builders" {
    item "Plugin devs" { icon: wrench }
    item "Template authors" { icon: doc }
    item "Integrators" { icon: puzzle }
  }
  ring "Ecosystem" {
    item "npm" { icon: cloud }
    item "GitHub" { icon: globe }
    item "Educators" { icon: book }
    item "Agencies" { icon: users }
  }
}`},
  },
  {
    id: 'flywheel',
    name: 'Flywheel',
    tagline: 'A self-reinforcing momentum loop of ring segments.',
    props: {vizType: 'flywheel', vizCategory: 'Business Frameworks', source: `viz flywheel "Marketplace Flywheel" {
  center: "Growth"
  item "More sellers" { icon: users }
  item "More selection" { icon: star }
  item "More buyers" { icon: heart }
  item "Lower prices" { icon: dollar }
}`},
  },
  {
    id: 'funnel',
    name: 'Funnel',
    tagline: 'Narrowing stages with side labels.',
    props: {vizType: 'funnel', vizCategory: 'Business Frameworks', source: `viz funnel "Sales Funnel" {
  input: "Potential customers"
  output: "Closed deals"
  item "Awareness" 5000
  item "Interest" 1800
  item "Evaluation" 420
  item "Negotiation" 120
  item "Won" 38
}`},
  },
  {
    id: 'hex-cluster',
    name: 'Hex cluster',
    tagline: 'A honeycomb — one core hexagon ringed by themed cells.',
    props: {vizType: 'hex-cluster', vizCategory: 'Business Frameworks', source: `viz hex-cluster "Team Health" {
  center "Team Health" { icon: heart }
  item "Clarity" { icon: target }
  item "Trust" { icon: handshake }
  item "Pace" { icon: rocket }
  item "Craft" { icon: gear }
  item "Growth" { icon: trend-up }
}`},
  },
  {
    id: 'okr',
    name: 'OKR',
    tagline: 'One objective branching into key results with progress bars.',
    props: {vizType: 'okr', vizCategory: 'Business Frameworks', source: `viz okr "Objective: Best-loved dev tool" {
  kr "NPS above 60" 0.72
  kr "P95 latency under 200ms" 0.45
  kr "10k weekly active teams" 0.31
}`},
  },
  {
    id: 'pestel',
    name: 'PESTEL',
    tagline: 'Six external-factor cards.',
    props: {vizType: 'pestel', vizCategory: 'Business Frameworks', source: `viz pestel "Market Environment" {
  item "Political" "Trade policy shifts" { item "Tariff changes" }
  item "Economic" "Rate environment" { item "Consumer spending" }
  item "Social" "Demographic trends" { item "Remote-first work" }
  item "Technological" "Rapid AI adoption" { item "Automation pressure" }
  item "Environmental" "Sustainability rules" { item "Carbon reporting" }
  item "Legal" "Data protection" { item "Privacy regulation" }
}`},
  },
  {
    id: 'porters',
    name: 'Porter\'s Five Forces',
    tagline: 'Competitive forces around a market.',
    props: {vizType: 'porters', vizCategory: 'Business Frameworks', source: `viz porters "Industry Forces" {
  item "Rivalry" "Many similar competitors"
  item "New entrants" "Low barriers to entry"
  item "Supplier power" "Few key suppliers"
  item "Buyer power" "Easy to switch"
  item "Substitutes" "DIY alternatives exist"
}`},
  },
  {
    id: 'pyramid',
    name: 'Pyramid',
    tagline: 'Stacked hierarchy levels.',
    props: {vizType: 'pyramid', vizCategory: 'Business Frameworks', source: `viz pyramid "Brand Pyramid" {
  item "Essence" "One promise"
  item "Personality" "How we sound and feel"
  item "Benefits" "What customers get"
  item "Attributes" "Features and facts"
}`},
  },
  {
    id: 'swot',
    name: 'SWOT',
    tagline: 'Strengths, weaknesses, opportunities, threats.',
    props: {vizType: 'swot', vizCategory: 'Business Frameworks', source: `viz swot "SWOT — Acme Corp" {
  item "Strengths" {
    item "Loyal customer base"
    item "Strong brand recognition"
  }
  item "Weaknesses" {
    item "Single revenue stream"
    item "Aging infrastructure"
  }
  item "Opportunities" {
    item "Emerging markets"
    item "AI-assisted workflows"
  }
  item "Threats" {
    item "New low-cost entrants"
    item "Tightening regulation"
  }
}`},
  },
  {
    id: 'value-chain',
    name: 'Value chain',
    tagline: 'A Porter-style chevron band with optional support bars.',
    props: {vizType: 'value-chain', vizCategory: 'Business Frameworks', source: `viz value-chain "How We Deliver" {
  support "Infrastructure & tooling"
  support "People & culture"
  item "Source" { icon: search }
  item "Build" { icon: wrench }
  item "Ship" { icon: rocket }
  item "Support" { icon: heart }
}`},
  },
  {
    id: 'domino',
    name: 'Domino',
    tagline: 'A chain reaction toppling left to right into the outcome.',
    props: {vizType: 'domino', vizCategory: 'Cause and Effect', source: `viz domino "How the Outage Spread" {
  item "Config typo" "Deployed on Friday"
  item "Cache stampede"
  item "API brownout"
  item "Checkout down" "43 minutes"
}`},
  },
  {
    id: 'fishbone',
    name: 'Fishbone',
    tagline: 'Ishikawa diagram — cause categories on angled bones along a spine.',
    props: {vizType: 'fishbone', vizCategory: 'Cause and Effect', source: `viz fishbone "Why Releases Slip" {
  bone "People" { item "Training gaps"; item "Turnover" }
  bone "Process" { item "No code review"; item "Manual QA" }
  bone "Tools" { item "Flaky CI" }
  bone "Environment" { item "Noisy office" }
}`},
  },
  {
    id: 'root-causes',
    name: 'Root causes',
    tagline: 'A tree whose roots carry the causes.',
    props: {vizType: 'root-causes', vizCategory: 'Cause and Effect', source: `viz root-causes "Why Releases Slip" {
  item "Unclear scope" "Requirements change mid-sprint"
  item "Hidden dependencies" "Teams discover coupling late"
  item "Manual testing" "QA becomes the bottleneck"
}`},
  },
  {
    id: 'balance',
    name: 'Balance',
    tagline: 'A balance scale weighing two sides.',
    props: {vizType: 'balance', vizCategory: 'Comparison', source: `viz balance "Work-Life Balance" {
  side "Career Growth" {
    item "Promotions" { icon: trend-up }
    item "Learning" { icon: book }
  }
  side "Personal Wellbeing" {
    item "Family time" { icon: heart }
    item "Health" { icon: leaf }
  }
}`},
  },
  {
    id: 'decision',
    name: 'Decision',
    tagline: 'A question fanning out to options.',
    props: {vizType: 'decision', vizCategory: 'Comparison', source: `viz decision "Where should we deploy?" {
  item "Cloud" "Fastest to start, elastic scale" { icon: cloud }
  item "On-prem" "Full control, higher ops load" { icon: database }
  item "Hybrid" "Sensitive data stays home" { icon: shield }
}`},
  },
  {
    id: 'decision-tree',
    name: 'Decision tree',
    tagline: 'Questions branching through labeled edges to outcomes.',
    props: {vizType: 'decision-tree', vizCategory: 'Comparison', source: `viz decision-tree {
  item "Build or buy?" {
    item "Core to product?" { when: "build" } {
      item "Build in-house" { when: "yes", icon: wrench }
      item "Open source + contribute" { when: "no", icon: globe }
    }
    item "Buy a vendor" { when: "buy", icon: dollar }
  }
}`},
  },
  {
    id: 'podium',
    name: 'Podium',
    tagline: '1-2-3 ranking blocks.',
    props: {vizType: 'podium', vizCategory: 'Comparison', source: `viz podium "Hackathon Winners" {
  item "Team Rocket" { icon: trophy }
  item "Null Pointers" { icon: medal }
  item "Bit Crushers" { icon: medal }
}`},
  },
  {
    id: 'pricing-tiers',
    name: 'Pricing tiers',
    tagline: 'Plan cards with prices and feature lists; highlight one tier.',
    props: {vizType: 'pricing-tiers', vizCategory: 'Comparison', source: `viz pricing-tiers "Plans" {
  period: "/mo"
  tier "Starter" 0 {
    item "3 projects"
    item "Community support"
  }
  tier "Pro" 29 { highlight: true
    item "Unlimited projects"
    item "SSO + RBAC"
    item "Priority support"
  }
  tier "Enterprise" 99 {
    item "Dedicated VPC"
    item "SLA + audit log"
    item "Onboarding team"
  }
}`},
  },
  {
    id: 'pros-and-cons',
    name: 'Pros and cons',
    tagline: 'Two panels weighing a decision.',
    props: {vizType: 'pros-and-cons', vizCategory: 'Comparison', source: `viz pros-and-cons "Remote Work" {
  pro "No commute time"
  pro "Global talent pool"
  pro "Lower office costs"
  pro "Flexible schedules"
  con "Harder to onboard juniors"
  con "Timezone coordination"
  con "Less spontaneous collaboration"
}`},
  },
  {
    id: 'quadrant',
    name: 'Quadrant',
    tagline: 'A 2×2 with axis labels; items in reading order TL, TR, BL, BR.',
    props: {vizType: 'quadrant', vizCategory: 'Comparison', source: `viz quadrant "Prioritization" {
  xLabels: ["Not urgent", "Urgent"]
  yLabels: ["Not important", "Important"]
  item "Schedule" "Plan deliberately" { icon: calendar }
  item "Do now" "Crises and deadlines" { icon: fire }
  item "Drop" "Time sinks" { icon: x }
  item "Delegate" "Interruptions, some email" { icon: users }
}`},
  },
  {
    id: 'relationship',
    name: 'Relationship',
    tagline: 'A hub with satellites on a dashed orbit.',
    props: {vizType: 'relationship', vizCategory: 'Comparison', source: `viz relationship "Product Ecosystem" {
  center "Platform" { icon: home }
  item "Mobile app" { icon: phone }
  item "API" { icon: gear }
  item "Marketplace" { icon: dollar }
  item "Analytics" { icon: chart }
  item "Community" { icon: users }
  item "Docs" { icon: book }
}`},
  },
  {
    id: 'spectrum',
    name: 'Spectrum',
    tagline: 'A range between two poles with zones.',
    props: {vizType: 'spectrum', vizCategory: 'Comparison', source: `viz spectrum "Working Styles" {
  item "Introvert" "Recharges alone, deep focus" { icon: book }
  item "Ambivert" "Adapts to the situation" { icon: scale }
  item "Extrovert" "Energized by people" { icon: users }
}`},
  },
  {
    id: 'table',
    name: 'Table',
    tagline: 'A comparison table with per-column accent colors.',
    props: {vizType: 'table', vizCategory: 'Comparison', source: `viz table "Plan Comparison" {
  header "Feature" ["Free", "Pro", "Enterprise"]
  row "Projects" ["3", "Unlimited", "Unlimited"]
  row "Members" ["5", "50", "Unlimited"]
  row "SSO" ["—", "—", "Included"]
  row "Support" ["Community", "Email", "Dedicated"]
}`},
  },
  {
    id: 'venn',
    name: 'Venn',
    tagline: 'Overlapping sets (2–7 circles) in a symmetric rosette, with region labels.',
    props: {vizType: 'venn', vizCategory: 'Comparison', source: `viz venn "Product Sweet Spot" {
  set "Desirable" "What users want" { icon: heart }
  set "Feasible" "What we can build" { icon: gear }
  set "Viable" "What sustains us" { icon: dollar }
  overlap all "Great products"
}`},
  },
  {
    id: 'versus',
    name: 'Versus',
    tagline: 'Head-to-head comparison across criteria.',
    props: {vizType: 'versus', vizCategory: 'Comparison', source: `viz versus "Buy vs Build" {
  left "Buy"
  right "Build"
  criterion "Time to value" { icon: clock, left: "Weeks", right: "Quarters" }
  criterion "Total cost" { icon: dollar, left: "Predictable subscription", right: "High upfront, low marginal" }
  criterion "Fit" { icon: puzzle, left: "80% out of the box", right: "Exactly your workflow" }
}`},
  },
  {
    id: 'area',
    name: 'Area chart',
    tagline: 'A line chart with a soft filled area underneath.',
    props: {vizType: 'area', vizCategory: 'Data', source: `viz area "Storage Used" {
  yTitle: "TB"
  item "2021" 14
  item "2022" 22
  item "2023" 31
  item "2024" 52
  item "2025" 78
}`},
  },
  {
    id: 'bar',
    name: 'Bar chart',
    tagline: 'Columns with per-category colors and value labels.',
    props: {vizType: 'bar', vizCategory: 'Data', source: `viz bar "Revenue by Quarter" {
  yTitle: "Revenue ($k)"
  item "Q1" 120
  item "Q2" 180
  item "Q3" 150
  item "Q4" 240
}`},
  },
  {
    id: 'bar-horizontal',
    name: 'Bar — horizontal',
    tagline: 'Horizontal bars with circular category badges.',
    props: {vizType: 'bar-horizontal', vizCategory: 'Data', source: `viz bar-horizontal "Team Capacity" {
  item "Engineering" 34 { icon: gear }
  item "Design" 12 { icon: heart }
  item "Marketing" 18 { icon: megaphone }
  item "Support" 22 { icon: chat }
}`},
  },
  {
    id: 'bullet-chart',
    name: 'Bullet chart',
    tagline: 'KPI rows — the actual bar vs a target tick.',
    props: {vizType: 'bullet-chart', vizCategory: 'Data', source: `viz bullet-chart "Q3 Scorecard" {
  kpi "Revenue" 74 90
  kpi "NPS" 61 55
  kpi "Uptime" 99.5 99.9
  kpi "Hiring" 6 10
}`},
  },
  {
    id: 'drop-off',
    name: 'Drop-off',
    tagline: 'Cascading stages, each smaller than the last.',
    props: {vizType: 'drop-off', vizCategory: 'Data', source: `viz drop-off "Signup Funnel Loss" {
  item "Visit" 100 { icon: eye }
  item "Sign up" 42 { icon: user }
  item "Activate" 18 { icon: check }
}`},
  },
  {
    id: 'dumbbell-horizontal',
    name: 'Dumbbell — horizontal',
    tagline: 'Progress tracks with a hanging value tag.',
    props: {vizType: 'dumbbell-horizontal', vizCategory: 'Data', source: `viz dumbbell-horizontal "Goal Progress" {
  item "Docs coverage" 80 "80%"
  item "Test coverage" 65 "65%"
  item "Accessibility" 90 "90%"
  item "Performance" 72 "72%"
}`},
  },
  {
    id: 'dumbbell-vertical',
    name: 'Dumbbell — vertical',
    tagline: 'Alternating capsules with a delta badge and connected notes.',
    props: {vizType: 'dumbbell-vertical', vizCategory: 'Data', source: `viz dumbbell-vertical "Year over Year" {
  item "Speed Score" "+15%" { icon: rocket, detail: "Increased from 70 to 85." }
  item "Retention" "+8%" { icon: heart, detail: "Now at 92% after onboarding fixes." }
  item "Cost per Lead" "-22%" { icon: dollar, detail: "Down from $18 to $14." }
}`},
  },
  {
    id: 'gauge',
    name: 'Gauge',
    tagline: 'A 270° dial for one value out of 100.',
    props: {vizType: 'gauge', vizCategory: 'Data', source: `viz gauge "System Health" {
  value: 87
  label: "Uptime score"
}`},
  },
  {
    id: 'heatmap',
    name: 'Heatmap',
    tagline: 'Intensity-shaded matrix cells — risk matrices, skills grids.',
    props: {vizType: 'heatmap', vizCategory: 'Data', source: `viz heatmap "Incidents per Service" {
  cols: ["Q1", "Q2", "Q3", "Q4"]
  row "API" [3, 5, 2, 1]
  row "Web" [1, 2, 1, 0]
  row "Billing" [4, 6, 5, 2]
  row "Auth" [0, 1, 3, 1]
}`},
  },
  {
    id: 'line',
    name: 'Line chart',
    tagline: 'A single series with point markers and value labels.',
    props: {vizType: 'line', vizCategory: 'Data', source: `viz line "Active Users" {
  yTitle: "Users"
  xTitle: "Month"
  item "Jan" 1200
  item "Feb" 1350
  item "Mar" 1600
  item "Apr" 1580
  item "May" 1900
  item "Jun" 2400
}`},
  },
  {
    id: 'pie',
    name: 'Pie chart',
    tagline: 'Slices with percentage callouts; alias donut for a hole.',
    props: {vizType: 'pie', vizCategory: 'Data', source: `viz pie "Market Share" {
  item "Alpha" 45 { icon: star }
  item "Beta" 30
  item "Gamma" 15
  item "Others" 10
}`},
  },
  {
    id: 'radar',
    name: 'Radar',
    tagline: 'A spider chart — series polygons over labeled axes.',
    props: {vizType: 'radar', vizCategory: 'Data', source: `viz radar "Platform Assessment" {
  axis "Security"
  axis "Performance"
  axis "Docs"
  axis "Ecosystem"
  axis "DX"
  series "Today" [3, 4, 2, 3, 2]
  series "Target" [5, 4, 4, 4, 5]
}`},
  },
  {
    id: 'sankey',
    name: 'Sankey',
    tagline: 'Sources flowing to targets with value-thick ribbons.',
    props: {vizType: 'sankey', vizCategory: 'Data', source: `viz sankey "Energy Mix" {
  flow "Coal" -> "Industry" 25
  flow "Coal" -> "Homes" 10
  flow "Solar" -> "Homes" 30
  flow "Solar" -> "Industry" 12
  flow "Wind" -> "Industry" 18
  flow "Wind" -> "Homes" 15
}`},
  },
  {
    id: 'slope-chart',
    name: 'Slope chart',
    tagline: 'Before → after lines, one per series.',
    props: {vizType: 'slope-chart', vizCategory: 'Data', source: `viz slope-chart "Ticket Volume" {
  left: "2026"
  right: "2027"
  item "Billing" 340 120
  item "Onboarding" 210 190
  item "API" 90 160
  item "Other" 150 60
}`},
  },
  {
    id: 'stacked-bar',
    name: 'Stacked bar',
    tagline: 'Stacked columns; legend via series entries.',
    props: {vizType: 'stacked-bar', vizCategory: 'Data', source: `viz stacked-bar "Budget by Quarter" {
  series "People"
  series "Tools"
  series "Marketing"
  item "Q1" [80, 20, 30]
  item "Q2" [90, 25, 45]
  item "Q3" [95, 22, 38]
}`},
  },
  {
    id: 'stacked-bar-horizontal',
    name: 'Stacked bar — horizontal',
    tagline: 'Horizontal stacked rows with a value axis.',
    props: {vizType: 'stacked-bar-horizontal', vizCategory: 'Data', source: `viz stacked-bar-horizontal "Department Budgets" {
  series "Salaries"
  series "Equipment"
  series "Travel"
  item "Engineering" [120000, 30000, 12000]
  item "Sales" [90000, 15000, 40000]
  item "Operations" [70000, 25000, 8000]
}`},
  },
  {
    id: 'waterfall',
    name: 'Waterfall',
    tagline: 'Start value, floating signed deltas, computed net.',
    props: {vizType: 'waterfall', vizCategory: 'Data', source: `viz waterfall "Cash Flow" {
  item "Opening" 500
  item "Rent" -200
  item "Payroll" -120
  item "Marketing" -40
  total "Closing"
}`},
  },
  {
    id: 'converge',
    name: 'Converge',
    tagline: 'Many inputs focused into one output.',
    props: {vizType: 'converge', vizCategory: 'Parts of a whole', source: `viz converge "Strategy Inputs" {
  item "Customer interviews" { icon: chat }
  item "Usage analytics" { icon: chart }
  item "Market research" { icon: search }
  item "Team retros" { icon: users }
  output "2026 Roadmap" { icon: doc }
}`},
  },
  {
    id: 'diverge',
    name: 'Diverge',
    tagline: 'One question radiating to options.',
    props: {vizType: 'diverge', vizCategory: 'Parts of a whole', source: `viz diverge "How might we grow?" {
  item "New markets" "Expand geographically" { icon: globe }
  item "New products" "Adjacent use cases" { icon: bulb }
  item "Partnerships" "Distribution through allies" { icon: handshake }
  item "Pricing" "Capture more value" { icon: dollar }
}`},
  },
  {
    id: 'iceberg',
    name: 'Iceberg',
    tagline: 'What\'s visible vs what lies beneath.',
    props: {vizType: 'iceberg', vizCategory: 'Parts of a whole', source: `viz iceberg "Project Effort" {
  above "The demo" "What stakeholders see" { icon: eye }
  below "Testing & hardening" "Edge cases, monitoring, rollback"
  below "Infrastructure" "CI, environments, data migrations"
}`},
  },
  {
    id: 'bridge',
    name: 'Bridge',
    tagline: 'Planks carrying you across the gap.',
    props: {vizType: 'bridge', vizCategory: 'Problems and Solutions', source: `viz bridge "Migration Plan" {
  from "Legacy stack" "Monolith on VMs"
  to "New platform" "Services on Kubernetes"
  item "Extract auth"
  item "Move billing"
  item "Split reporting"
  item "Retire monolith"
  action: "One service at a time"
}`},
  },
  {
    id: 'challenges',
    name: 'Challenges',
    tagline: 'Hurdles spanning the gap between now and the goal.',
    props: {vizType: 'challenges', vizCategory: 'Problems and Solutions', source: `viz challenges "Path to Launch" {
  from "Prototype" "Works on my machine"
  to "Production" "Reliable for everyone"
  item "Security review" "Close the audit findings"
  item "Scale testing" "Survive 10x load"
  item "Compliance" "SOC 2 evidence complete"
  action: "Bridge the gap"
}`},
  },
  {
    id: 'problem-solution',
    name: 'Problem / solution',
    tagline: 'A problem transformed through a central solution.',
    props: {vizType: 'problem-solution', vizCategory: 'Problems and Solutions', source: `viz problem-solution "Support Overload" {
  problem "Ticket backlog" "400 open tickets, 3-day replies"
  solution "Self-serve help center"
  outcome "Faster answers" "70% deflection, same-day replies"
  support "Smooth migration for existing users"
  support "Weekly content reviews keep articles fresh"
}`},
  },
  {
    id: 'transformation',
    name: 'Transformation',
    tagline: 'Before → after, chaos settling into order.',
    props: {vizType: 'transformation', vizCategory: 'Problems and Solutions', source: `viz transformation "Workflow Cleanup" {
  before "Manual chaos" "Spreadsheets and email threads"
  after "Streamlined flow" "One automated pipeline"
}`},
  },
  {
    id: 'cycle',
    name: 'Cycle',
    tagline: 'Phases on a ring with sweeping arrows; adapts from 3 to 6+ phases.',
    props: {vizType: 'cycle', vizCategory: 'Process', source: `viz cycle "Build-Measure-Learn" {
  item "Build" "Ship the smallest useful slice" { icon: gear }
  item "Measure" "Watch real usage, not opinions" { icon: chart }
  item "Learn" "Decide: persevere or pivot" { icon: bulb }
}`},
  },
  {
    id: 'flowchart',
    name: 'Flowchart',
    tagline: 'Sequential steps with arrows; set direction: right for a horizontal chain.',
    props: {vizType: 'flowchart', vizCategory: 'Process', source: `viz flowchart "Content Publishing" {
  item "Draft" { icon: doc }
  item "Review" { icon: search }
  item "Approve" { icon: check }
  item "Publish" { icon: rocket }
}`},
  },
  {
    id: 'gantt',
    name: 'Gantt',
    tagline: 'Cascading task bars over a time grid, with an optional deadline.',
    props: {vizType: 'gantt', vizCategory: 'Process', source: `viz gantt "Release Plan" {
  scale: ["Wk 1", "Wk 2", "Wk 3", "Wk 4", "Wk 5", "Wk 6"]
  deadline: 5
  task "Design" 0 1.5
  task "Build" 1 3.5
  task "QA" 3 4.5
  task "Rollout" 4.5 5
}`},
  },
  {
    id: 'journey',
    name: 'Journey',
    tagline: 'A winding road with numbered stops.',
    props: {vizType: 'journey', vizCategory: 'Process', source: `viz journey "User Journey" {
  item "Discover" "Finds us via search or a friend"
  item "Try" "Signs up for the free tier"
  item "Adopt" "Invites the team, builds a habit"
  item "Upgrade" "Converts to a paid plan"
  item "Advocate" "Recommends us to others"
}`},
  },
  {
    id: 'kanban',
    name: 'Kanban',
    tagline: 'Named columns of cards — the task board.',
    props: {vizType: 'kanban', vizCategory: 'Process', source: `viz kanban "Sprint 12" {
  column "To do" {
    item "Rate limiting"
    item "Billing webhooks"
    item "Dark mode"
  }
  column "Doing" {
    item "Checkout flow" { icon: fire }
    item "SSO login"
  }
  column "Done" {
    item "Search rework" { icon: check }
    item "Onboarding tour" { icon: check }
  }
}`},
  },
  {
    id: 'sequence',
    name: 'Sequence',
    tagline: 'Numbered step panels flowing in reading order (boustrophedon).',
    props: {vizType: 'sequence', vizCategory: 'Process', source: `viz sequence "Customer Onboarding" {
  item "Sign up" "Create an account with email or SSO."
  item "Verify" "Confirm the email address."
  item "Profile" "Add team and workspace details."
  item "Invite" "Bring in the first teammates."
  item "Import" "Load existing project data."
  item "Launch" "Go live with the first project."
}`},
  },
  {
    id: 'stairs',
    name: 'Stairs',
    tagline: 'Ascending steps toward a goal.',
    props: {vizType: 'stairs', vizCategory: 'Process', source: `viz stairs "Growth Ladder" {
  item "Learn" { icon: book }
  item "Build" { icon: gear }
  item "Ship" { icon: rocket }
  item "Scale" { icon: trend-up }
}`},
  },
  {
    id: 'swimlane-flow',
    name: 'Swimlane flow',
    tagline: 'A flowchart over responsibility lanes — who does what, in order.',
    props: {vizType: 'swimlane-flow', vizCategory: 'Process', source: `viz swimlane-flow "Release Process" {
  lane "Product" {
    step "Spec" 0 { icon: doc }
    step "Sign-off" 3 { icon: check }
  }
  lane "Engineering" {
    step "Build" 1 { icon: wrench }
    step "Deploy" 4 { icon: rocket }
  }
  lane "QA" {
    step "Test" 2 { icon: search }
  }
}`},
  },
  {
    id: 'milestone-path',
    name: 'Milestone path',
    tagline: 'A winding trail to the summit flag, milestones along the way.',
    props: {vizType: 'milestone-path', vizCategory: 'Timelines', source: `viz milestone-path "Road to Launch" {
  item "Prototype" "Q1 — clickable demo"
  item "Private beta" "Q2 — 20 design partners"
  item "Pricing" "Q3 — packaging locked"
  goal "Launch" "Public GA"
}`},
  },
  {
    id: 'roadmap-lanes',
    name: 'Roadmap lanes',
    tagline: 'Workstream swimlanes across quarters — the product-roadmap slide.',
    props: {vizType: 'roadmap-lanes', vizCategory: 'Timelines', source: `viz roadmap-lanes "2027 Roadmap" {
  scale: ["Q1", "Q2", "Q3", "Q4"]
  lane "Platform" {
    task "SSO + RBAC" 0 1.5
    task "Audit log" 2 3
    icon: gear
  }
  lane "Growth" {
    task "Referrals" 0.5 2
    milestone "Self-serve GA" 3
    icon: trend-up
  }
  lane "Mobile" {
    task "iOS beta" 1 2.5
    task "Android" 2.5 4
    icon: phone
  }
}`},
  },
  {
    id: 'timeline',
    name: 'Timeline',
    tagline: 'Events along a dashed baseline, alternating up/down.',
    props: {vizType: 'timeline', vizCategory: 'Timelines', source: `viz timeline "Company Milestones" {
  item "2019" "Founded in a garage" { icon: home }
  item "2021" "First 1,000 customers" { icon: users }
  item "2023" "Series A raised" { icon: dollar }
  item "2025" "Global expansion" { icon: globe }
}`},
  },
  {
    id: 'bottleneck',
    name: 'Bottleneck',
    tagline: 'Flow crowding into a narrow neck.',
    props: {vizType: 'bottleneck', vizCategory: 'Visual Metaphors', source: `viz bottleneck "Review Bottleneck" {
  in: "30 PRs/week"
  out: "8 merged"
  neck: "Two reviewers"
}`},
  },
  {
    id: 'dialogue',
    name: 'Dialogue',
    tagline: 'A conversation in speech bubbles.',
    props: {vizType: 'dialogue', vizCategory: 'Visual Metaphors', source: `viz dialogue "Discovery Call" {
  a: "Customer"
  b: "Sales"
  msg "We spend hours copying data between tools." { speaker: a }
  msg "What would change if that sync was automatic?" { speaker: b }
  msg "We'd save a day a week, easily." { speaker: a }
  msg "Let me show you how the integration works." { speaker: b }
}`},
  },
  {
    id: 'impact',
    name: 'Impact',
    tagline: 'One cause radiating to effects.',
    props: {vizType: 'impact', vizCategory: 'Visual Metaphors', source: `viz impact "Faster Releases" {
  cause "Weekly ship cadence"
  item "Happier customers" "Fixes land in days, not months"
  item "Tighter feedback" "Real usage guides the roadmap"
  item "Team momentum" "Small wins compound"
}`},
  },
  {
    id: 'lens',
    name: 'Lens',
    tagline: 'Inputs focused through a lens into one outcome.',
    props: {vizType: 'lens', vizCategory: 'Visual Metaphors', source: `viz lens "Research Focus" {
  item "Interviews" { icon: chat }
  item "Surveys" { icon: doc }
  item "Analytics" { icon: chart }
  output "Insight report" { icon: bulb }
}`},
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    tagline: 'A beam sweeping over labeled rocks — guidance past the risks.',
    props: {vizType: 'lighthouse', vizCategory: 'Visual Metaphors', source: `viz lighthouse "Compliance Guidance" {
  ship: "Launch plan"
  item "Data residency" "EU hosting required"
  item "Audit gaps" "SOC 2 evidence missing"
  item "Access sprawl" "Stale admin accounts"
}`},
  },
  {
    id: 'magnet',
    name: 'Magnet',
    tagline: 'A horseshoe magnet pulling item chips in — attraction and retention.',
    props: {vizType: 'magnet', vizCategory: 'Visual Metaphors', source: `viz magnet "Why Devs Stay" {
  label: "Developer experience"
  item "Fast CI" { icon: rocket }
  item "Clear docs" { icon: book }
  item "Small PRs" { icon: check }
  item "Owned services" { icon: shield }
}`},
  },
  {
    id: 'performance',
    name: 'Performance',
    tagline: 'Side-by-side donut gauges.',
    props: {vizType: 'performance', vizCategory: 'Visual Metaphors', source: `viz performance "Quarterly KPIs" {
  summary: "All three programs are trending above target."
  item "Uptime" 99 "Rolling 90-day availability" { icon: shield }
  item "NPS" 62 "Promoters minus detractors" { icon: heart }
  item "Velocity" 85 "Committed vs delivered" { icon: rocket }
}`},
  },
  {
    id: 'pillar',
    name: 'Pillar',
    tagline: 'Classical columns holding up the mission.',
    props: {vizType: 'pillar', vizCategory: 'Visual Metaphors', source: `viz pillar "Company Pillars" {
  item "Trust" "Security and reliability first" { icon: shield }
  item "Craft" "Quality in every detail" { icon: star }
  item "Pace" "Ship and learn weekly" { icon: rocket }
  item "Care" "Customers and each other" { icon: heart }
}`},
  },
  {
    id: 'prism',
    name: 'Prism',
    tagline: 'One input refracted into many outputs.',
    props: {vizType: 'prism', vizCategory: 'Visual Metaphors', source: `viz prism "One Strategy, Many Wins" {
  input "Platform bet" { icon: diamond }
  item "Faster features" { icon: rocket }
  item "Lower costs" { icon: dollar }
  item "New integrations" { icon: puzzle }
  item "Happier devs" { icon: heart }
}`},
  },
  {
    id: 'race',
    name: 'Race',
    tagline: 'Contestants approaching the finish line.',
    props: {vizType: 'race', vizCategory: 'Visual Metaphors', source: `viz race "Market Race" {
  item "Us"
  item "Competitor X"
}`},
  },
  {
    id: 'trend',
    name: 'Trend',
    tagline: 'A staircase climbing up and to the right.',
    props: {vizType: 'trend', vizCategory: 'Visual Metaphors', source: `viz trend "Maturity Curve" {
  item "Ad hoc" "Heroics and hotfixes" { icon: fire }
  item "Repeatable" "Checklists and runbooks" { icon: doc }
  item "Automated" "CI/CD end to end" { icon: gear }
  item "Self-healing" "Systems fix themselves" { icon: star }
}`},
  },
];

export const VIZ_TEMPLATE_COUNT = 82;
export const VIZ_EXCLUDED = ["personas","vision","hole","tug-of-war","quote"] as const;
export const VIZ_CATEGORIES = ["Brainstorming","Business Frameworks","Cause and Effect","Comparison","Data","Parts of a whole","Problems and Solutions","Process","Timelines","Visual Metaphors"] as const;
