// AUTO-GENERATED by scripts/build-registry.mjs — do not edit.
// Run `npm run registry` after adding or removing an effect.
import type {EffectEntry} from './types';
import {AudioSpectrum as C_AudioSpectrum} from './effects/audio/audio-spectrum/AudioSpectrum';
import {meta as M_AudioSpectrum} from './effects/audio/audio-spectrum/meta';
import {Audiogram as C_Audiogram} from './effects/audio/audiogram/Audiogram';
import {meta as M_Audiogram} from './effects/audio/audiogram/meta';
import {AuroraMesh as C_AuroraMesh} from './effects/backgrounds/aurora-mesh/AuroraMesh';
import {meta as M_AuroraMesh} from './effects/backgrounds/aurora-mesh/meta';
import {DotGridPulse as C_DotGridPulse} from './effects/backgrounds/dot-grid-pulse/DotGridPulse';
import {meta as M_DotGridPulse} from './effects/backgrounds/dot-grid-pulse/meta';
import {FloatingShapes as C_FloatingShapes} from './effects/backgrounds/floating-shapes/FloatingShapes';
import {meta as M_FloatingShapes} from './effects/backgrounds/floating-shapes/meta';
import {RetroGridFloor as C_RetroGridFloor} from './effects/backgrounds/retro-grid-floor/RetroGridFloor';
import {meta as M_RetroGridFloor} from './effects/backgrounds/retro-grid-floor/meta';
import {HypeCaptions as C_HypeCaptions} from './effects/captions/hype-captions/HypeCaptions';
import {meta as M_HypeCaptions} from './effects/captions/hype-captions/meta';
import {KaraokeBand as C_KaraokeBand} from './effects/captions/karaoke-band/KaraokeBand';
import {meta as M_KaraokeBand} from './effects/captions/karaoke-band/meta';
import {TikTokCaptions as C_TikTokCaptions} from './effects/captions/tiktok-captions/TikTokCaptions';
import {meta as M_TikTokCaptions} from './effects/captions/tiktok-captions/meta';
import {BarChartRace as C_BarChartRace} from './effects/data/bar-chart-race/BarChartRace';
import {meta as M_BarChartRace} from './effects/data/bar-chart-race/meta';
import {BubblePack as C_BubblePack} from './effects/data/bubble-pack/BubblePack';
import {meta as M_BubblePack} from './effects/data/bubble-pack/meta';
import {BulletPopList as C_BulletPopList} from './effects/data/bullet-pop-list/BulletPopList';
import {meta as M_BulletPopList} from './effects/data/bullet-pop-list/meta';
import {ChordDiagram as C_ChordDiagram} from './effects/data/chord-diagram/ChordDiagram';
import {meta as M_ChordDiagram} from './effects/data/chord-diagram/meta';
import {CountUpStat as C_CountUpStat} from './effects/data/count-up-stat/CountUpStat';
import {meta as M_CountUpStat} from './effects/data/count-up-stat/meta';
import {DonutProgress as C_DonutProgress} from './effects/data/donut-progress/DonutProgress';
import {meta as M_DonutProgress} from './effects/data/donut-progress/meta';
import {ForceNetwork as C_ForceNetwork} from './effects/data/force-network/ForceNetwork';
import {meta as M_ForceNetwork} from './effects/data/force-network/meta';
import {GlobeArcs as C_GlobeArcs} from './effects/data/globe-arcs/GlobeArcs';
import {meta as M_GlobeArcs} from './effects/data/globe-arcs/meta';
import {LineChartDraw as C_LineChartDraw} from './effects/data/line-chart-draw/LineChartDraw';
import {meta as M_LineChartDraw} from './effects/data/line-chart-draw/meta';
import {SankeyFlow as C_SankeyFlow} from './effects/data/sankey-flow/SankeyFlow';
import {meta as M_SankeyFlow} from './effects/data/sankey-flow/meta';
import {Streamgraph as C_Streamgraph} from './effects/data/streamgraph/Streamgraph';
import {meta as M_Streamgraph} from './effects/data/streamgraph/meta';
import {SunburstRings as C_SunburstRings} from './effects/data/sunburst-rings/SunburstRings';
import {meta as M_SunburstRings} from './effects/data/sunburst-rings/meta';
import {VersusTable as C_VersusTable} from './effects/data/versus-table/VersusTable';
import {meta as M_VersusTable} from './effects/data/versus-table/meta';
import {VoronoiShatter as C_VoronoiShatter} from './effects/data/voronoi-shatter/VoronoiShatter';
import {meta as M_VoronoiShatter} from './effects/data/voronoi-shatter/meta';
import {EffectsCatalogue as C_EffectsCatalogue} from './effects/effects/effects-catalogue/EffectsCatalogue';
import {meta as M_EffectsCatalogue} from './effects/effects/effects-catalogue/meta';
import {HalftonePrint as C_HalftonePrint} from './effects/effects/halftone-print/HalftonePrint';
import {meta as M_HalftonePrint} from './effects/effects/halftone-print/meta';
import {MetaballGoo as C_MetaballGoo} from './effects/effects/metaball-goo/MetaballGoo';
import {meta as M_MetaballGoo} from './effects/effects/metaball-goo/meta';
import {PixelDissolveReveal as C_PixelDissolveReveal} from './effects/effects/pixel-dissolve-reveal/PixelDissolveReveal';
import {meta as M_PixelDissolveReveal} from './effects/effects/pixel-dissolve-reveal/meta';
import {ProgressiveBlurFocus as C_ProgressiveBlurFocus} from './effects/effects/progressive-blur-focus/ProgressiveBlurFocus';
import {meta as M_ProgressiveBlurFocus} from './effects/effects/progressive-blur-focus/meta';
import {VhsVintage as C_VhsVintage} from './effects/effects/vhs-vintage/VhsVintage';
import {meta as M_VhsVintage} from './effects/effects/vhs-vintage/meta';
import {BeforeAfterWipe as C_BeforeAfterWipe} from './effects/media/before-after-wipe/BeforeAfterWipe';
import {meta as M_BeforeAfterWipe} from './effects/media/before-after-wipe/meta';
import {KenBurns as C_KenBurns} from './effects/media/ken-burns/KenBurns';
import {meta as M_KenBurns} from './effects/media/ken-burns/meta';
import {MaskRevealKit as C_MaskRevealKit} from './effects/media/mask-reveal-kit/MaskRevealKit';
import {meta as M_MaskRevealKit} from './effects/media/mask-reveal-kit/meta';
import {PhotoStackShuffle as C_PhotoStackShuffle} from './effects/media/photo-stack-shuffle/PhotoStackShuffle';
import {meta as M_PhotoStackShuffle} from './effects/media/photo-stack-shuffle/meta';
import {TextBehindSubject as C_TextBehindSubject} from './effects/media/text-behind-subject/TextBehindSubject';
import {meta as M_TextBehindSubject} from './effects/media/text-behind-subject/meta';
import {VideoInText as C_VideoInText} from './effects/media/video-in-text/VideoInText';
import {meta as M_VideoInText} from './effects/media/video-in-text/meta';
import {AttentionIndicators as C_AttentionIndicators} from './effects/motion/attention-indicators/AttentionIndicators';
import {meta as M_AttentionIndicators} from './effects/motion/attention-indicators/meta';
import {FreezeTrail as C_FreezeTrail} from './effects/motion/freeze-trail/FreezeTrail';
import {meta as M_FreezeTrail} from './effects/motion/freeze-trail/meta';
import {LogoPathDraw as C_LogoPathDraw} from './effects/motion/logo-path-draw/LogoPathDraw';
import {meta as M_LogoPathDraw} from './effects/motion/logo-path-draw/meta';
import {MagicMoveCard as C_MagicMoveCard} from './effects/motion/magic-move-card/MagicMoveCard';
import {meta as M_MagicMoveCard} from './effects/motion/magic-move-card/meta';
import {MagicMoveGallery as C_MagicMoveGallery} from './effects/motion/magic-move-gallery/MagicMoveGallery';
import {meta as M_MagicMoveGallery} from './effects/motion/magic-move-gallery/meta';
import {OrbitSystem as C_OrbitSystem} from './effects/motion/orbit-system/OrbitSystem';
import {meta as M_OrbitSystem} from './effects/motion/orbit-system/meta';
import {ParallaxLayers as C_ParallaxLayers} from './effects/motion/parallax-layers/ParallaxLayers';
import {meta as M_ParallaxLayers} from './effects/motion/parallax-layers/meta';
import {ParticleField as C_ParticleField} from './effects/motion/particle-field/ParticleField';
import {meta as M_ParticleField} from './effects/motion/particle-field/meta';
import {RouteFlyover as C_RouteFlyover} from './effects/motion/route-flyover/RouteFlyover';
import {meta as M_RouteFlyover} from './effects/motion/route-flyover/meta';
import {ShapeMorph as C_ShapeMorph} from './effects/motion/shape-morph/ShapeMorph';
import {meta as M_ShapeMorph} from './effects/motion/shape-morph/meta';
import {ChapterDivider as C_ChapterDivider} from './effects/openers/chapter-divider/ChapterDivider';
import {meta as M_ChapterDivider} from './effects/openers/chapter-divider/meta';
import {CinematicTechIntro as C_CinematicTechIntro} from './effects/openers/cinematic-tech-intro/CinematicTechIntro';
import {meta as M_CinematicTechIntro} from './effects/openers/cinematic-tech-intro/meta';
import {CountdownLeader as C_CountdownLeader} from './effects/openers/countdown-leader/CountdownLeader';
import {meta as M_CountdownLeader} from './effects/openers/countdown-leader/meta';
import {DeviceRise as C_DeviceRise} from './effects/openers/device-rise/DeviceRise';
import {meta as M_DeviceRise} from './effects/openers/device-rise/meta';
import {StatSlam as C_StatSlam} from './effects/openers/stat-slam/StatSlam';
import {meta as M_StatSlam} from './effects/openers/stat-slam/meta';
import {CharDropSpring as C_CharDropSpring} from './effects/text/char-drop-spring/CharDropSpring';
import {meta as M_CharDropSpring} from './effects/text/char-drop-spring/meta';
import {GlitchText as C_GlitchText} from './effects/text/glitch-text/GlitchText';
import {meta as M_GlitchText} from './effects/text/glitch-text/meta';
import {GradientTextSweep as C_GradientTextSweep} from './effects/text/gradient-text-sweep/GradientTextSweep';
import {meta as M_GradientTextSweep} from './effects/text/gradient-text-sweep/meta';
import {HandAnnotations as C_HandAnnotations} from './effects/text/hand-annotations/HandAnnotations';
import {meta as M_HandAnnotations} from './effects/text/hand-annotations/meta';
import {HeadlineHighlight as C_HeadlineHighlight} from './effects/text/headline-highlight/HeadlineHighlight';
import {meta as M_HeadlineHighlight} from './effects/text/headline-highlight/meta';
import {KineticWordReveal as C_KineticWordReveal} from './effects/text/kinetic-word-reveal/KineticWordReveal';
import {meta as M_KineticWordReveal} from './effects/text/kinetic-word-reveal/meta';
import {QuoteSlam as C_QuoteSlam} from './effects/text/quote-slam/QuoteSlam';
import {meta as M_QuoteSlam} from './effects/text/quote-slam/meta';
import {SplitFlapBoard as C_SplitFlapBoard} from './effects/text/split-flap-board/SplitFlapBoard';
import {meta as M_SplitFlapBoard} from './effects/text/split-flap-board/meta';
import {TextMaskReveal as C_TextMaskReveal} from './effects/text/text-mask-reveal/TextMaskReveal';
import {meta as M_TextMaskReveal} from './effects/text/text-mask-reveal/meta';
import {TextScramble as C_TextScramble} from './effects/text/text-scramble/TextScramble';
import {meta as M_TextScramble} from './effects/text/text-scramble/meta';
import {TypewriterTerminal as C_TypewriterTerminal} from './effects/text/typewriter-terminal/TypewriterTerminal';
import {meta as M_TypewriterTerminal} from './effects/text/typewriter-terminal/meta';
import {WriteOnText as C_WriteOnText} from './effects/text/write-on-text/WriteOnText';
import {meta as M_WriteOnText} from './effects/text/write-on-text/meta';
import {CssCardFlip as C_CssCardFlip} from './effects/three-d/css-card-flip/CssCardFlip';
import {meta as M_CssCardFlip} from './effects/three-d/css-card-flip/meta';
import {DnaHelix as C_DnaHelix} from './effects/three-d/dna-helix/DnaHelix';
import {meta as M_DnaHelix} from './effects/three-d/dna-helix/meta';
import {ExtrudedText as C_ExtrudedText} from './effects/three-d/extruded-text/ExtrudedText';
import {meta as M_ExtrudedText} from './effects/three-d/extruded-text/meta';
import {GalaxyParticles as C_GalaxyParticles} from './effects/three-d/galaxy-particles/GalaxyParticles';
import {meta as M_GalaxyParticles} from './effects/three-d/galaxy-particles/meta';
import {GlassRefraction as C_GlassRefraction} from './effects/three-d/glass-refraction/GlassRefraction';
import {meta as M_GlassRefraction} from './effects/three-d/glass-refraction/meta';
import {InfiniteTunnel as C_InfiniteTunnel} from './effects/three-d/infinite-tunnel/InfiniteTunnel';
import {meta as M_InfiniteTunnel} from './effects/three-d/infinite-tunnel/meta';
import {InstancedCubeWave as C_InstancedCubeWave} from './effects/three-d/instanced-cube-wave/InstancedCubeWave';
import {meta as M_InstancedCubeWave} from './effects/three-d/instanced-cube-wave/meta';
import {ShaderBlob as C_ShaderBlob} from './effects/three-d/shader-blob/ShaderBlob';
import {meta as M_ShaderBlob} from './effects/three-d/shader-blob/meta';
import {ThreeRotatingLogo as C_ThreeRotatingLogo} from './effects/three-d/three-rotating-logo/ThreeRotatingLogo';
import {meta as M_ThreeRotatingLogo} from './effects/three-d/three-rotating-logo/meta';
import {CustomCircleReveal as C_CustomCircleReveal} from './effects/transitions/custom-circle-reveal/CustomCircleReveal';
import {meta as M_CustomCircleReveal} from './effects/transitions/custom-circle-reveal/meta';
import {LightLeakTransition as C_LightLeakTransition} from './effects/transitions/light-leak-transition/LightLeakTransition';
import {meta as M_LightLeakTransition} from './effects/transitions/light-leak-transition/meta';
import {TransitionSampler as C_TransitionSampler} from './effects/transitions/transition-sampler/TransitionSampler';
import {meta as M_TransitionSampler} from './effects/transitions/transition-sampler/meta';
import {WhipPan as C_WhipPan} from './effects/transitions/whip-pan/WhipPan';
import {meta as M_WhipPan} from './effects/transitions/whip-pan/meta';
import {BrowserWindowScroll as C_BrowserWindowScroll} from './effects/ui/browser-window-scroll/BrowserWindowScroll';
import {meta as M_BrowserWindowScroll} from './effects/ui/browser-window-scroll/meta';
import {ChatConversation as C_ChatConversation} from './effects/ui/chat-conversation/ChatConversation';
import {meta as M_ChatConversation} from './effects/ui/chat-conversation/meta';
import {ChatThreadLive as C_ChatThreadLive} from './effects/ui/chat-thread-live/ChatThreadLive';
import {meta as M_ChatThreadLive} from './effects/ui/chat-thread-live/meta';
import {ChatGptComposer as C_ChatGptComposer} from './effects/ui/chatgpt-composer/ChatGptComposer';
import {meta as M_ChatGptComposer} from './effects/ui/chatgpt-composer/meta';
import {ChatGptFullUi as C_ChatGptFullUi} from './effects/ui/chatgpt-full-ui/ChatGptFullUi';
import {meta as M_ChatGptFullUi} from './effects/ui/chatgpt-full-ui/meta';
import {ChecklistTicks as C_ChecklistTicks} from './effects/ui/checklist-ticks/ChecklistTicks';
import {meta as M_ChecklistTicks} from './effects/ui/checklist-ticks/meta';
import {ClaudeFullUi as C_ClaudeFullUi} from './effects/ui/claude-full-ui/ClaudeFullUi';
import {meta as M_ClaudeFullUi} from './effects/ui/claude-full-ui/meta';
import {CodeEditorTyping as C_CodeEditorTyping} from './effects/ui/code-editor-typing/CodeEditorTyping';
import {meta as M_CodeEditorTyping} from './effects/ui/code-editor-typing/meta';
import {GeminiFullUi as C_GeminiFullUi} from './effects/ui/gemini-full-ui/GeminiFullUi';
import {meta as M_GeminiFullUi} from './effects/ui/gemini-full-ui/meta';
import {LowerThird as C_LowerThird} from './effects/ui/lower-third/LowerThird';
import {meta as M_LowerThird} from './effects/ui/lower-third/meta';
import {NotificationStack as C_NotificationStack} from './effects/ui/notification-stack/NotificationStack';
import {meta as M_NotificationStack} from './effects/ui/notification-stack/meta';
import {StepProgress as C_StepProgress} from './effects/ui/step-progress/StepProgress';
import {meta as M_StepProgress} from './effects/ui/step-progress/meta';
import {SubscribeButton as C_SubscribeButton} from './effects/ui/subscribe-button/SubscribeButton';
import {meta as M_SubscribeButton} from './effects/ui/subscribe-button/meta';

export const effects: readonly EffectEntry[] = [
  {meta: M_AudioSpectrum, Component: C_AudioSpectrum as React.ComponentType, file: 'audio/audio-spectrum/AudioSpectrum.tsx'},
  {meta: M_Audiogram, Component: C_Audiogram as React.ComponentType, file: 'audio/audiogram/Audiogram.tsx'},
  {meta: M_AuroraMesh, Component: C_AuroraMesh as React.ComponentType, file: 'backgrounds/aurora-mesh/AuroraMesh.tsx'},
  {meta: M_DotGridPulse, Component: C_DotGridPulse as React.ComponentType, file: 'backgrounds/dot-grid-pulse/DotGridPulse.tsx'},
  {meta: M_FloatingShapes, Component: C_FloatingShapes as React.ComponentType, file: 'backgrounds/floating-shapes/FloatingShapes.tsx'},
  {meta: M_RetroGridFloor, Component: C_RetroGridFloor as React.ComponentType, file: 'backgrounds/retro-grid-floor/RetroGridFloor.tsx'},
  {meta: M_HypeCaptions, Component: C_HypeCaptions as React.ComponentType, file: 'captions/hype-captions/HypeCaptions.tsx'},
  {meta: M_KaraokeBand, Component: C_KaraokeBand as React.ComponentType, file: 'captions/karaoke-band/KaraokeBand.tsx'},
  {meta: M_TikTokCaptions, Component: C_TikTokCaptions as React.ComponentType, file: 'captions/tiktok-captions/TikTokCaptions.tsx'},
  {meta: M_BarChartRace, Component: C_BarChartRace as React.ComponentType, file: 'data/bar-chart-race/BarChartRace.tsx'},
  {meta: M_BubblePack, Component: C_BubblePack as React.ComponentType, file: 'data/bubble-pack/BubblePack.tsx'},
  {meta: M_BulletPopList, Component: C_BulletPopList as React.ComponentType, file: 'data/bullet-pop-list/BulletPopList.tsx'},
  {meta: M_ChordDiagram, Component: C_ChordDiagram as React.ComponentType, file: 'data/chord-diagram/ChordDiagram.tsx'},
  {meta: M_CountUpStat, Component: C_CountUpStat as React.ComponentType, file: 'data/count-up-stat/CountUpStat.tsx'},
  {meta: M_DonutProgress, Component: C_DonutProgress as React.ComponentType, file: 'data/donut-progress/DonutProgress.tsx'},
  {meta: M_ForceNetwork, Component: C_ForceNetwork as React.ComponentType, file: 'data/force-network/ForceNetwork.tsx'},
  {meta: M_GlobeArcs, Component: C_GlobeArcs as React.ComponentType, file: 'data/globe-arcs/GlobeArcs.tsx'},
  {meta: M_LineChartDraw, Component: C_LineChartDraw as React.ComponentType, file: 'data/line-chart-draw/LineChartDraw.tsx'},
  {meta: M_SankeyFlow, Component: C_SankeyFlow as React.ComponentType, file: 'data/sankey-flow/SankeyFlow.tsx'},
  {meta: M_Streamgraph, Component: C_Streamgraph as React.ComponentType, file: 'data/streamgraph/Streamgraph.tsx'},
  {meta: M_SunburstRings, Component: C_SunburstRings as React.ComponentType, file: 'data/sunburst-rings/SunburstRings.tsx'},
  {meta: M_VersusTable, Component: C_VersusTable as React.ComponentType, file: 'data/versus-table/VersusTable.tsx'},
  {meta: M_VoronoiShatter, Component: C_VoronoiShatter as React.ComponentType, file: 'data/voronoi-shatter/VoronoiShatter.tsx'},
  {meta: M_EffectsCatalogue, Component: C_EffectsCatalogue as React.ComponentType, file: 'effects/effects-catalogue/EffectsCatalogue.tsx'},
  {meta: M_HalftonePrint, Component: C_HalftonePrint as React.ComponentType, file: 'effects/halftone-print/HalftonePrint.tsx'},
  {meta: M_MetaballGoo, Component: C_MetaballGoo as React.ComponentType, file: 'effects/metaball-goo/MetaballGoo.tsx'},
  {meta: M_PixelDissolveReveal, Component: C_PixelDissolveReveal as React.ComponentType, file: 'effects/pixel-dissolve-reveal/PixelDissolveReveal.tsx'},
  {meta: M_ProgressiveBlurFocus, Component: C_ProgressiveBlurFocus as React.ComponentType, file: 'effects/progressive-blur-focus/ProgressiveBlurFocus.tsx'},
  {meta: M_VhsVintage, Component: C_VhsVintage as React.ComponentType, file: 'effects/vhs-vintage/VhsVintage.tsx'},
  {meta: M_BeforeAfterWipe, Component: C_BeforeAfterWipe as React.ComponentType, file: 'media/before-after-wipe/BeforeAfterWipe.tsx'},
  {meta: M_KenBurns, Component: C_KenBurns as React.ComponentType, file: 'media/ken-burns/KenBurns.tsx'},
  {meta: M_MaskRevealKit, Component: C_MaskRevealKit as React.ComponentType, file: 'media/mask-reveal-kit/MaskRevealKit.tsx'},
  {meta: M_PhotoStackShuffle, Component: C_PhotoStackShuffle as React.ComponentType, file: 'media/photo-stack-shuffle/PhotoStackShuffle.tsx'},
  {meta: M_TextBehindSubject, Component: C_TextBehindSubject as React.ComponentType, file: 'media/text-behind-subject/TextBehindSubject.tsx'},
  {meta: M_VideoInText, Component: C_VideoInText as React.ComponentType, file: 'media/video-in-text/VideoInText.tsx'},
  {meta: M_AttentionIndicators, Component: C_AttentionIndicators as React.ComponentType, file: 'motion/attention-indicators/AttentionIndicators.tsx'},
  {meta: M_FreezeTrail, Component: C_FreezeTrail as React.ComponentType, file: 'motion/freeze-trail/FreezeTrail.tsx'},
  {meta: M_LogoPathDraw, Component: C_LogoPathDraw as React.ComponentType, file: 'motion/logo-path-draw/LogoPathDraw.tsx'},
  {meta: M_MagicMoveCard, Component: C_MagicMoveCard as React.ComponentType, file: 'motion/magic-move-card/MagicMoveCard.tsx'},
  {meta: M_MagicMoveGallery, Component: C_MagicMoveGallery as React.ComponentType, file: 'motion/magic-move-gallery/MagicMoveGallery.tsx'},
  {meta: M_OrbitSystem, Component: C_OrbitSystem as React.ComponentType, file: 'motion/orbit-system/OrbitSystem.tsx'},
  {meta: M_ParallaxLayers, Component: C_ParallaxLayers as React.ComponentType, file: 'motion/parallax-layers/ParallaxLayers.tsx'},
  {meta: M_ParticleField, Component: C_ParticleField as React.ComponentType, file: 'motion/particle-field/ParticleField.tsx'},
  {meta: M_RouteFlyover, Component: C_RouteFlyover as React.ComponentType, file: 'motion/route-flyover/RouteFlyover.tsx'},
  {meta: M_ShapeMorph, Component: C_ShapeMorph as React.ComponentType, file: 'motion/shape-morph/ShapeMorph.tsx'},
  {meta: M_ChapterDivider, Component: C_ChapterDivider as React.ComponentType, file: 'openers/chapter-divider/ChapterDivider.tsx'},
  {meta: M_CinematicTechIntro, Component: C_CinematicTechIntro as React.ComponentType, file: 'openers/cinematic-tech-intro/CinematicTechIntro.tsx'},
  {meta: M_CountdownLeader, Component: C_CountdownLeader as React.ComponentType, file: 'openers/countdown-leader/CountdownLeader.tsx'},
  {meta: M_DeviceRise, Component: C_DeviceRise as React.ComponentType, file: 'openers/device-rise/DeviceRise.tsx'},
  {meta: M_StatSlam, Component: C_StatSlam as React.ComponentType, file: 'openers/stat-slam/StatSlam.tsx'},
  {meta: M_CharDropSpring, Component: C_CharDropSpring as React.ComponentType, file: 'text/char-drop-spring/CharDropSpring.tsx'},
  {meta: M_GlitchText, Component: C_GlitchText as React.ComponentType, file: 'text/glitch-text/GlitchText.tsx'},
  {meta: M_GradientTextSweep, Component: C_GradientTextSweep as React.ComponentType, file: 'text/gradient-text-sweep/GradientTextSweep.tsx'},
  {meta: M_HandAnnotations, Component: C_HandAnnotations as React.ComponentType, file: 'text/hand-annotations/HandAnnotations.tsx'},
  {meta: M_HeadlineHighlight, Component: C_HeadlineHighlight as React.ComponentType, file: 'text/headline-highlight/HeadlineHighlight.tsx'},
  {meta: M_KineticWordReveal, Component: C_KineticWordReveal as React.ComponentType, file: 'text/kinetic-word-reveal/KineticWordReveal.tsx'},
  {meta: M_QuoteSlam, Component: C_QuoteSlam as React.ComponentType, file: 'text/quote-slam/QuoteSlam.tsx'},
  {meta: M_SplitFlapBoard, Component: C_SplitFlapBoard as React.ComponentType, file: 'text/split-flap-board/SplitFlapBoard.tsx'},
  {meta: M_TextMaskReveal, Component: C_TextMaskReveal as React.ComponentType, file: 'text/text-mask-reveal/TextMaskReveal.tsx'},
  {meta: M_TextScramble, Component: C_TextScramble as React.ComponentType, file: 'text/text-scramble/TextScramble.tsx'},
  {meta: M_TypewriterTerminal, Component: C_TypewriterTerminal as React.ComponentType, file: 'text/typewriter-terminal/TypewriterTerminal.tsx'},
  {meta: M_WriteOnText, Component: C_WriteOnText as React.ComponentType, file: 'text/write-on-text/WriteOnText.tsx'},
  {meta: M_CssCardFlip, Component: C_CssCardFlip as React.ComponentType, file: 'three-d/css-card-flip/CssCardFlip.tsx'},
  {meta: M_DnaHelix, Component: C_DnaHelix as React.ComponentType, file: 'three-d/dna-helix/DnaHelix.tsx'},
  {meta: M_ExtrudedText, Component: C_ExtrudedText as React.ComponentType, file: 'three-d/extruded-text/ExtrudedText.tsx'},
  {meta: M_GalaxyParticles, Component: C_GalaxyParticles as React.ComponentType, file: 'three-d/galaxy-particles/GalaxyParticles.tsx'},
  {meta: M_GlassRefraction, Component: C_GlassRefraction as React.ComponentType, file: 'three-d/glass-refraction/GlassRefraction.tsx'},
  {meta: M_InfiniteTunnel, Component: C_InfiniteTunnel as React.ComponentType, file: 'three-d/infinite-tunnel/InfiniteTunnel.tsx'},
  {meta: M_InstancedCubeWave, Component: C_InstancedCubeWave as React.ComponentType, file: 'three-d/instanced-cube-wave/InstancedCubeWave.tsx'},
  {meta: M_ShaderBlob, Component: C_ShaderBlob as React.ComponentType, file: 'three-d/shader-blob/ShaderBlob.tsx'},
  {meta: M_ThreeRotatingLogo, Component: C_ThreeRotatingLogo as React.ComponentType, file: 'three-d/three-rotating-logo/ThreeRotatingLogo.tsx'},
  {meta: M_CustomCircleReveal, Component: C_CustomCircleReveal as React.ComponentType, file: 'transitions/custom-circle-reveal/CustomCircleReveal.tsx'},
  {meta: M_LightLeakTransition, Component: C_LightLeakTransition as React.ComponentType, file: 'transitions/light-leak-transition/LightLeakTransition.tsx'},
  {meta: M_TransitionSampler, Component: C_TransitionSampler as React.ComponentType, file: 'transitions/transition-sampler/TransitionSampler.tsx'},
  {meta: M_WhipPan, Component: C_WhipPan as React.ComponentType, file: 'transitions/whip-pan/WhipPan.tsx'},
  {meta: M_BrowserWindowScroll, Component: C_BrowserWindowScroll as React.ComponentType, file: 'ui/browser-window-scroll/BrowserWindowScroll.tsx'},
  {meta: M_ChatConversation, Component: C_ChatConversation as React.ComponentType, file: 'ui/chat-conversation/ChatConversation.tsx'},
  {meta: M_ChatThreadLive, Component: C_ChatThreadLive as React.ComponentType, file: 'ui/chat-thread-live/ChatThreadLive.tsx'},
  {meta: M_ChatGptComposer, Component: C_ChatGptComposer as React.ComponentType, file: 'ui/chatgpt-composer/ChatGptComposer.tsx'},
  {meta: M_ChatGptFullUi, Component: C_ChatGptFullUi as React.ComponentType, file: 'ui/chatgpt-full-ui/ChatGptFullUi.tsx'},
  {meta: M_ChecklistTicks, Component: C_ChecklistTicks as React.ComponentType, file: 'ui/checklist-ticks/ChecklistTicks.tsx'},
  {meta: M_ClaudeFullUi, Component: C_ClaudeFullUi as React.ComponentType, file: 'ui/claude-full-ui/ClaudeFullUi.tsx'},
  {meta: M_CodeEditorTyping, Component: C_CodeEditorTyping as React.ComponentType, file: 'ui/code-editor-typing/CodeEditorTyping.tsx'},
  {meta: M_GeminiFullUi, Component: C_GeminiFullUi as React.ComponentType, file: 'ui/gemini-full-ui/GeminiFullUi.tsx'},
  {meta: M_LowerThird, Component: C_LowerThird as React.ComponentType, file: 'ui/lower-third/LowerThird.tsx'},
  {meta: M_NotificationStack, Component: C_NotificationStack as React.ComponentType, file: 'ui/notification-stack/NotificationStack.tsx'},
  {meta: M_StepProgress, Component: C_StepProgress as React.ComponentType, file: 'ui/step-progress/StepProgress.tsx'},
  {meta: M_SubscribeButton, Component: C_SubscribeButton as React.ComponentType, file: 'ui/subscribe-button/SubscribeButton.tsx'},
];

export const effectById = (id: string) => effects.find((e) => e.meta.id === id);

/**
 * Everything in public/. staticFile() returns a ROOT-absolute path with no way
 * to prefix a base, so a gallery served from a subpath (GitHub Pages project
 * sites, for instance) has to remap these before the app mounts. See
 * src/gallery/main.tsx.
 */
export const publicAssets: readonly string[] = [
  'plate-1.svg',
  'plate-2.svg',
  'plate-3.svg',
  'plate-4.svg',
  'plate-5.svg',
  'sample-audio.mp3',
  'sample-city.svg',
  'sample-scene.svg',
  'subject-skyline.svg',
];
