// AUTO-GENERATED by scripts/build-registry.mjs — do not edit.
// Run `npm run registry` after adding or removing an effect.
import type {EffectEntry} from './types';
import {AuroraMesh as C_AuroraMesh} from './effects/backgrounds/aurora-mesh/AuroraMesh';
import {meta as M_AuroraMesh} from './effects/backgrounds/aurora-mesh/meta';
import {DotGridPulse as C_DotGridPulse} from './effects/backgrounds/dot-grid-pulse/DotGridPulse';
import {meta as M_DotGridPulse} from './effects/backgrounds/dot-grid-pulse/meta';
import {FloatingShapes as C_FloatingShapes} from './effects/backgrounds/floating-shapes/FloatingShapes';
import {meta as M_FloatingShapes} from './effects/backgrounds/floating-shapes/meta';
import {RetroGridFloor as C_RetroGridFloor} from './effects/backgrounds/retro-grid-floor/RetroGridFloor';
import {meta as M_RetroGridFloor} from './effects/backgrounds/retro-grid-floor/meta';
import {PauseAwareCaptions as C_PauseAwareCaptions} from './effects/captions/pause-aware-captions/PauseAwareCaptions';
import {meta as M_PauseAwareCaptions} from './effects/captions/pause-aware-captions/meta';
import {SubtitleBand as C_SubtitleBand} from './effects/captions/subtitle-band/SubtitleBand';
import {meta as M_SubtitleBand} from './effects/captions/subtitle-band/meta';
import {TiktokCaptions as C_TiktokCaptions} from './effects/captions/tiktok-captions/TiktokCaptions';
import {meta as M_TiktokCaptions} from './effects/captions/tiktok-captions/meta';
import {BarChartRace as C_BarChartRace} from './effects/charts/bar-chart-race/BarChartRace';
import {meta as M_BarChartRace} from './effects/charts/bar-chart-race/meta';
import {BubblePack as C_BubblePack} from './effects/charts/bubble-pack/BubblePack';
import {meta as M_BubblePack} from './effects/charts/bubble-pack/meta';
import {ChordDiagram as C_ChordDiagram} from './effects/charts/chord-diagram/ChordDiagram';
import {meta as M_ChordDiagram} from './effects/charts/chord-diagram/meta';
import {CountUpStat as C_CountUpStat} from './effects/charts/count-up-stat/CountUpStat';
import {meta as M_CountUpStat} from './effects/charts/count-up-stat/meta';
import {DonutProgress as C_DonutProgress} from './effects/charts/donut-progress/DonutProgress';
import {meta as M_DonutProgress} from './effects/charts/donut-progress/meta';
import {ForceNetwork as C_ForceNetwork} from './effects/charts/force-network/ForceNetwork';
import {meta as M_ForceNetwork} from './effects/charts/force-network/meta';
import {GlobeArcs as C_GlobeArcs} from './effects/charts/globe-arcs/GlobeArcs';
import {meta as M_GlobeArcs} from './effects/charts/globe-arcs/meta';
import {LineChartDraw as C_LineChartDraw} from './effects/charts/line-chart-draw/LineChartDraw';
import {meta as M_LineChartDraw} from './effects/charts/line-chart-draw/meta';
import {RouteFlyover as C_RouteFlyover} from './effects/charts/route-flyover/RouteFlyover';
import {meta as M_RouteFlyover} from './effects/charts/route-flyover/meta';
import {SankeyFlow as C_SankeyFlow} from './effects/charts/sankey-flow/SankeyFlow';
import {meta as M_SankeyFlow} from './effects/charts/sankey-flow/meta';
import {Streamgraph as C_Streamgraph} from './effects/charts/streamgraph/Streamgraph';
import {meta as M_Streamgraph} from './effects/charts/streamgraph/meta';
import {SunburstRings as C_SunburstRings} from './effects/charts/sunburst-rings/SunburstRings';
import {meta as M_SunburstRings} from './effects/charts/sunburst-rings/meta';
import {VersusTable as C_VersusTable} from './effects/charts/versus-table/VersusTable';
import {meta as M_VersusTable} from './effects/charts/versus-table/meta';
import {AttentionIndicators as C_AttentionIndicators} from './effects/diagrams/attention-indicators/AttentionIndicators';
import {meta as M_AttentionIndicators} from './effects/diagrams/attention-indicators/meta';
import {BulletPopList as C_BulletPopList} from './effects/diagrams/bullet-pop-list/BulletPopList';
import {meta as M_BulletPopList} from './effects/diagrams/bullet-pop-list/meta';
import {ChecklistTicks as C_ChecklistTicks} from './effects/diagrams/checklist-ticks/ChecklistTicks';
import {meta as M_ChecklistTicks} from './effects/diagrams/checklist-ticks/meta';
import {HandAnnotations as C_HandAnnotations} from './effects/diagrams/hand-annotations/HandAnnotations';
import {meta as M_HandAnnotations} from './effects/diagrams/hand-annotations/meta';
import {LogoPathDraw as C_LogoPathDraw} from './effects/diagrams/logo-path-draw/LogoPathDraw';
import {meta as M_LogoPathDraw} from './effects/diagrams/logo-path-draw/meta';
import {ShapeMorph as C_ShapeMorph} from './effects/diagrams/shape-morph/ShapeMorph';
import {meta as M_ShapeMorph} from './effects/diagrams/shape-morph/meta';
import {StepProgress as C_StepProgress} from './effects/diagrams/step-progress/StepProgress';
import {meta as M_StepProgress} from './effects/diagrams/step-progress/meta';
import {VizGallery as C_VizGallery} from './effects/diagrams/viz-gallery/VizGallery';
import {meta as M_VizGallery} from './effects/diagrams/viz-gallery/meta';
import {WriteOnText as C_WriteOnText} from './effects/diagrams/write-on-text/WriteOnText';
import {meta as M_WriteOnText} from './effects/diagrams/write-on-text/meta';
import {BeforeAfterWipe as C_BeforeAfterWipe} from './effects/edit/before-after-wipe/BeforeAfterWipe';
import {meta as M_BeforeAfterWipe} from './effects/edit/before-after-wipe/meta';
import {DesignedPause as C_DesignedPause} from './effects/edit/designed-pause/DesignedPause';
import {meta as M_DesignedPause} from './effects/edit/designed-pause/meta';
import {FreezeTrail as C_FreezeTrail} from './effects/edit/freeze-trail/FreezeTrail';
import {meta as M_FreezeTrail} from './effects/edit/freeze-trail/meta';
import {HandheldDrift as C_HandheldDrift} from './effects/edit/handheld-drift/HandheldDrift';
import {meta as M_HandheldDrift} from './effects/edit/handheld-drift/meta';
import {KenBurns as C_KenBurns} from './effects/edit/ken-burns/KenBurns';
import {meta as M_KenBurns} from './effects/edit/ken-burns/meta';
import {PhotoStackShuffle as C_PhotoStackShuffle} from './effects/edit/photo-stack-shuffle/PhotoStackShuffle';
import {meta as M_PhotoStackShuffle} from './effects/edit/photo-stack-shuffle/meta';
import {PunchInCut as C_PunchInCut} from './effects/edit/punch-in-cut/PunchInCut';
import {meta as M_PunchInCut} from './effects/edit/punch-in-cut/meta';
import {SilenceCut as C_SilenceCut} from './effects/edit/silence-cut/SilenceCut';
import {meta as M_SilenceCut} from './effects/edit/silence-cut/meta';
import {SpeedRamp as C_SpeedRamp} from './effects/edit/speed-ramp/SpeedRamp';
import {meta as M_SpeedRamp} from './effects/edit/speed-ramp/meta';
import {FilmGrade as C_FilmGrade} from './effects/grade/film-grade/FilmGrade';
import {meta as M_FilmGrade} from './effects/grade/film-grade/meta';
import {ProgressiveBlurFocus as C_ProgressiveBlurFocus} from './effects/grade/progressive-blur-focus/ProgressiveBlurFocus';
import {meta as M_ProgressiveBlurFocus} from './effects/grade/progressive-blur-focus/meta';
import {GlitchText as C_GlitchText} from './effects/looks/glitch-text/GlitchText';
import {meta as M_GlitchText} from './effects/looks/glitch-text/meta';
import {HalftonePrint as C_HalftonePrint} from './effects/looks/halftone-print/HalftonePrint';
import {meta as M_HalftonePrint} from './effects/looks/halftone-print/meta';
import {MetaballGoo as C_MetaballGoo} from './effects/looks/metaball-goo/MetaballGoo';
import {meta as M_MetaballGoo} from './effects/looks/metaball-goo/meta';
import {PixelDissolveReveal as C_PixelDissolveReveal} from './effects/looks/pixel-dissolve-reveal/PixelDissolveReveal';
import {meta as M_PixelDissolveReveal} from './effects/looks/pixel-dissolve-reveal/meta';
import {VhsVintage as C_VhsVintage} from './effects/looks/vhs-vintage/VhsVintage';
import {meta as M_VhsVintage} from './effects/looks/vhs-vintage/meta';
import {AspectMorphCard as C_AspectMorphCard} from './effects/motion/aspect-morph-card/AspectMorphCard';
import {meta as M_AspectMorphCard} from './effects/motion/aspect-morph-card/meta';
import {GridToHero as C_GridToHero} from './effects/motion/grid-to-hero/GridToHero';
import {meta as M_GridToHero} from './effects/motion/grid-to-hero/meta';
import {OrbitSystem as C_OrbitSystem} from './effects/motion/orbit-system/OrbitSystem';
import {meta as M_OrbitSystem} from './effects/motion/orbit-system/meta';
import {ParallaxLayers as C_ParallaxLayers} from './effects/motion/parallax-layers/ParallaxLayers';
import {meta as M_ParallaxLayers} from './effects/motion/parallax-layers/meta';
import {ParticleField as C_ParticleField} from './effects/motion/particle-field/ParticleField';
import {meta as M_ParticleField} from './effects/motion/particle-field/meta';
import {EffectsCatalogue as C_EffectsCatalogue} from './effects/reference/effects-catalogue/EffectsCatalogue';
import {meta as M_EffectsCatalogue} from './effects/reference/effects-catalogue/meta';
import {MaskRevealKit as C_MaskRevealKit} from './effects/reference/mask-reveal-kit/MaskRevealKit';
import {meta as M_MaskRevealKit} from './effects/reference/mask-reveal-kit/meta';
import {TransitionSampler as C_TransitionSampler} from './effects/reference/transition-sampler/TransitionSampler';
import {meta as M_TransitionSampler} from './effects/reference/transition-sampler/meta';
import {HypeCaptions as C_HypeCaptions} from './effects/social/hype-captions/HypeCaptions';
import {meta as M_HypeCaptions} from './effects/social/hype-captions/meta';
import {ImessageLive as C_ImessageLive} from './effects/social/imessage-live/ImessageLive';
import {meta as M_ImessageLive} from './effects/social/imessage-live/meta';
import {ImessageThread as C_ImessageThread} from './effects/social/imessage-thread/ImessageThread';
import {meta as M_ImessageThread} from './effects/social/imessage-thread/meta';
import {SubscribeButton as C_SubscribeButton} from './effects/social/subscribe-button/SubscribeButton';
import {meta as M_SubscribeButton} from './effects/social/subscribe-button/meta';
import {Audiogram as C_Audiogram} from './effects/sound/audiogram/Audiogram';
import {meta as M_Audiogram} from './effects/sound/audiogram/meta';
import {FftBars as C_FftBars} from './effects/sound/fft-bars/FftBars';
import {meta as M_FftBars} from './effects/sound/fft-bars/meta';
import {DnaHelix as C_DnaHelix} from './effects/three-d/dna-helix/DnaHelix';
import {meta as M_DnaHelix} from './effects/three-d/dna-helix/meta';
import {GalaxyParticles as C_GalaxyParticles} from './effects/three-d/galaxy-particles/GalaxyParticles';
import {meta as M_GalaxyParticles} from './effects/three-d/galaxy-particles/meta';
import {GlassRefraction as C_GlassRefraction} from './effects/three-d/glass-refraction/GlassRefraction';
import {meta as M_GlassRefraction} from './effects/three-d/glass-refraction/meta';
import {InfiniteTunnel as C_InfiniteTunnel} from './effects/three-d/infinite-tunnel/InfiniteTunnel';
import {meta as M_InfiniteTunnel} from './effects/three-d/infinite-tunnel/meta';
import {InstancedCubeWave as C_InstancedCubeWave} from './effects/three-d/instanced-cube-wave/InstancedCubeWave';
import {meta as M_InstancedCubeWave} from './effects/three-d/instanced-cube-wave/meta';
import {ShaderBlob as C_ShaderBlob} from './effects/three-d/shader-blob/ShaderBlob';
import {meta as M_ShaderBlob} from './effects/three-d/shader-blob/meta';
import {ThreeRotatingLogo as C_ThreeRotatingLogo} from './effects/three-d/three-rotating-logo/ThreeRotatingLogo';
import {meta as M_ThreeRotatingLogo} from './effects/three-d/three-rotating-logo/meta';
import {ChapterDivider as C_ChapterDivider} from './effects/titles/chapter-divider/ChapterDivider';
import {meta as M_ChapterDivider} from './effects/titles/chapter-divider/meta';
import {CinematicTechIntro as C_CinematicTechIntro} from './effects/titles/cinematic-tech-intro/CinematicTechIntro';
import {meta as M_CinematicTechIntro} from './effects/titles/cinematic-tech-intro/meta';
import {CountdownLeader as C_CountdownLeader} from './effects/titles/countdown-leader/CountdownLeader';
import {meta as M_CountdownLeader} from './effects/titles/countdown-leader/meta';
import {LowerThird as C_LowerThird} from './effects/titles/lower-third/LowerThird';
import {meta as M_LowerThird} from './effects/titles/lower-third/meta';
import {QuoteSlam as C_QuoteSlam} from './effects/titles/quote-slam/QuoteSlam';
import {meta as M_QuoteSlam} from './effects/titles/quote-slam/meta';
import {StatSlam as C_StatSlam} from './effects/titles/stat-slam/StatSlam';
import {meta as M_StatSlam} from './effects/titles/stat-slam/meta';
import {CssCardFlip as C_CssCardFlip} from './effects/transitions/css-card-flip/CssCardFlip';
import {meta as M_CssCardFlip} from './effects/transitions/css-card-flip/meta';
import {CustomCircleReveal as C_CustomCircleReveal} from './effects/transitions/custom-circle-reveal/CustomCircleReveal';
import {meta as M_CustomCircleReveal} from './effects/transitions/custom-circle-reveal/meta';
import {LightLeakTransition as C_LightLeakTransition} from './effects/transitions/light-leak-transition/LightLeakTransition';
import {meta as M_LightLeakTransition} from './effects/transitions/light-leak-transition/meta';
import {VoronoiShatter as C_VoronoiShatter} from './effects/transitions/voronoi-shatter/VoronoiShatter';
import {meta as M_VoronoiShatter} from './effects/transitions/voronoi-shatter/meta';
import {WhipPan as C_WhipPan} from './effects/transitions/whip-pan/WhipPan';
import {meta as M_WhipPan} from './effects/transitions/whip-pan/meta';
import {CharDropSpring as C_CharDropSpring} from './effects/type/char-drop-spring/CharDropSpring';
import {meta as M_CharDropSpring} from './effects/type/char-drop-spring/meta';
import {ExtrudedText as C_ExtrudedText} from './effects/type/extruded-text/ExtrudedText';
import {meta as M_ExtrudedText} from './effects/type/extruded-text/meta';
import {GradientTextSweep as C_GradientTextSweep} from './effects/type/gradient-text-sweep/GradientTextSweep';
import {meta as M_GradientTextSweep} from './effects/type/gradient-text-sweep/meta';
import {HeadlineHighlight as C_HeadlineHighlight} from './effects/type/headline-highlight/HeadlineHighlight';
import {meta as M_HeadlineHighlight} from './effects/type/headline-highlight/meta';
import {KineticWordReveal as C_KineticWordReveal} from './effects/type/kinetic-word-reveal/KineticWordReveal';
import {meta as M_KineticWordReveal} from './effects/type/kinetic-word-reveal/meta';
import {SplitFlapBoard as C_SplitFlapBoard} from './effects/type/split-flap-board/SplitFlapBoard';
import {meta as M_SplitFlapBoard} from './effects/type/split-flap-board/meta';
import {TextBehindSubject as C_TextBehindSubject} from './effects/type/text-behind-subject/TextBehindSubject';
import {meta as M_TextBehindSubject} from './effects/type/text-behind-subject/meta';
import {TextMaskReveal as C_TextMaskReveal} from './effects/type/text-mask-reveal/TextMaskReveal';
import {meta as M_TextMaskReveal} from './effects/type/text-mask-reveal/meta';
import {TextScramble as C_TextScramble} from './effects/type/text-scramble/TextScramble';
import {meta as M_TextScramble} from './effects/type/text-scramble/meta';
import {TypewriterTerminal as C_TypewriterTerminal} from './effects/type/typewriter-terminal/TypewriterTerminal';
import {meta as M_TypewriterTerminal} from './effects/type/typewriter-terminal/meta';
import {VideoInText as C_VideoInText} from './effects/type/video-in-text/VideoInText';
import {meta as M_VideoInText} from './effects/type/video-in-text/meta';
import {BrowserWindowScroll as C_BrowserWindowScroll} from './effects/ui/browser-window-scroll/BrowserWindowScroll';
import {meta as M_BrowserWindowScroll} from './effects/ui/browser-window-scroll/meta';
import {ChatgptFullUi as C_ChatgptFullUi} from './effects/ui/chatgpt-full-ui/ChatgptFullUi';
import {meta as M_ChatgptFullUi} from './effects/ui/chatgpt-full-ui/meta';
import {ClaudeFullUi as C_ClaudeFullUi} from './effects/ui/claude-full-ui/ClaudeFullUi';
import {meta as M_ClaudeFullUi} from './effects/ui/claude-full-ui/meta';
import {CodeEditorTyping as C_CodeEditorTyping} from './effects/ui/code-editor-typing/CodeEditorTyping';
import {meta as M_CodeEditorTyping} from './effects/ui/code-editor-typing/meta';
import {DeviceRise as C_DeviceRise} from './effects/ui/device-rise/DeviceRise';
import {meta as M_DeviceRise} from './effects/ui/device-rise/meta';
import {HeroHandoverUi as C_HeroHandoverUi} from './effects/ui/hero-handover-ui/HeroHandoverUi';
import {meta as M_HeroHandoverUi} from './effects/ui/hero-handover-ui/meta';
import {NotificationStack as C_NotificationStack} from './effects/ui/notification-stack/NotificationStack';
import {meta as M_NotificationStack} from './effects/ui/notification-stack/meta';

/** One entry per folder, before variant expansion. */
const base: readonly EffectEntry[] = [
  {meta: M_AuroraMesh, Component: C_AuroraMesh as React.ComponentType, file: 'backgrounds/aurora-mesh/AuroraMesh.tsx'},
  {meta: M_DotGridPulse, Component: C_DotGridPulse as React.ComponentType, file: 'backgrounds/dot-grid-pulse/DotGridPulse.tsx'},
  {meta: M_FloatingShapes, Component: C_FloatingShapes as React.ComponentType, file: 'backgrounds/floating-shapes/FloatingShapes.tsx'},
  {meta: M_RetroGridFloor, Component: C_RetroGridFloor as React.ComponentType, file: 'backgrounds/retro-grid-floor/RetroGridFloor.tsx'},
  {meta: M_PauseAwareCaptions, Component: C_PauseAwareCaptions as React.ComponentType, file: 'captions/pause-aware-captions/PauseAwareCaptions.tsx'},
  {meta: M_SubtitleBand, Component: C_SubtitleBand as React.ComponentType, file: 'captions/subtitle-band/SubtitleBand.tsx'},
  {meta: M_TiktokCaptions, Component: C_TiktokCaptions as React.ComponentType, file: 'captions/tiktok-captions/TiktokCaptions.tsx'},
  {meta: M_BarChartRace, Component: C_BarChartRace as React.ComponentType, file: 'charts/bar-chart-race/BarChartRace.tsx'},
  {meta: M_BubblePack, Component: C_BubblePack as React.ComponentType, file: 'charts/bubble-pack/BubblePack.tsx'},
  {meta: M_ChordDiagram, Component: C_ChordDiagram as React.ComponentType, file: 'charts/chord-diagram/ChordDiagram.tsx'},
  {meta: M_CountUpStat, Component: C_CountUpStat as React.ComponentType, file: 'charts/count-up-stat/CountUpStat.tsx'},
  {meta: M_DonutProgress, Component: C_DonutProgress as React.ComponentType, file: 'charts/donut-progress/DonutProgress.tsx'},
  {meta: M_ForceNetwork, Component: C_ForceNetwork as React.ComponentType, file: 'charts/force-network/ForceNetwork.tsx'},
  {meta: M_GlobeArcs, Component: C_GlobeArcs as React.ComponentType, file: 'charts/globe-arcs/GlobeArcs.tsx'},
  {meta: M_LineChartDraw, Component: C_LineChartDraw as React.ComponentType, file: 'charts/line-chart-draw/LineChartDraw.tsx'},
  {meta: M_RouteFlyover, Component: C_RouteFlyover as React.ComponentType, file: 'charts/route-flyover/RouteFlyover.tsx'},
  {meta: M_SankeyFlow, Component: C_SankeyFlow as React.ComponentType, file: 'charts/sankey-flow/SankeyFlow.tsx'},
  {meta: M_Streamgraph, Component: C_Streamgraph as React.ComponentType, file: 'charts/streamgraph/Streamgraph.tsx'},
  {meta: M_SunburstRings, Component: C_SunburstRings as React.ComponentType, file: 'charts/sunburst-rings/SunburstRings.tsx'},
  {meta: M_VersusTable, Component: C_VersusTable as React.ComponentType, file: 'charts/versus-table/VersusTable.tsx'},
  {meta: M_AttentionIndicators, Component: C_AttentionIndicators as React.ComponentType, file: 'diagrams/attention-indicators/AttentionIndicators.tsx'},
  {meta: M_BulletPopList, Component: C_BulletPopList as React.ComponentType, file: 'diagrams/bullet-pop-list/BulletPopList.tsx'},
  {meta: M_ChecklistTicks, Component: C_ChecklistTicks as React.ComponentType, file: 'diagrams/checklist-ticks/ChecklistTicks.tsx'},
  {meta: M_HandAnnotations, Component: C_HandAnnotations as React.ComponentType, file: 'diagrams/hand-annotations/HandAnnotations.tsx'},
  {meta: M_LogoPathDraw, Component: C_LogoPathDraw as React.ComponentType, file: 'diagrams/logo-path-draw/LogoPathDraw.tsx'},
  {meta: M_ShapeMorph, Component: C_ShapeMorph as React.ComponentType, file: 'diagrams/shape-morph/ShapeMorph.tsx'},
  {meta: M_StepProgress, Component: C_StepProgress as React.ComponentType, file: 'diagrams/step-progress/StepProgress.tsx'},
  {meta: M_VizGallery, Component: C_VizGallery as React.ComponentType, file: 'diagrams/viz-gallery/VizGallery.tsx'},
  {meta: M_WriteOnText, Component: C_WriteOnText as React.ComponentType, file: 'diagrams/write-on-text/WriteOnText.tsx'},
  {meta: M_BeforeAfterWipe, Component: C_BeforeAfterWipe as React.ComponentType, file: 'edit/before-after-wipe/BeforeAfterWipe.tsx'},
  {meta: M_DesignedPause, Component: C_DesignedPause as React.ComponentType, file: 'edit/designed-pause/DesignedPause.tsx'},
  {meta: M_FreezeTrail, Component: C_FreezeTrail as React.ComponentType, file: 'edit/freeze-trail/FreezeTrail.tsx'},
  {meta: M_HandheldDrift, Component: C_HandheldDrift as React.ComponentType, file: 'edit/handheld-drift/HandheldDrift.tsx'},
  {meta: M_KenBurns, Component: C_KenBurns as React.ComponentType, file: 'edit/ken-burns/KenBurns.tsx'},
  {meta: M_PhotoStackShuffle, Component: C_PhotoStackShuffle as React.ComponentType, file: 'edit/photo-stack-shuffle/PhotoStackShuffle.tsx'},
  {meta: M_PunchInCut, Component: C_PunchInCut as React.ComponentType, file: 'edit/punch-in-cut/PunchInCut.tsx'},
  {meta: M_SilenceCut, Component: C_SilenceCut as React.ComponentType, file: 'edit/silence-cut/SilenceCut.tsx'},
  {meta: M_SpeedRamp, Component: C_SpeedRamp as React.ComponentType, file: 'edit/speed-ramp/SpeedRamp.tsx'},
  {meta: M_FilmGrade, Component: C_FilmGrade as React.ComponentType, file: 'grade/film-grade/FilmGrade.tsx'},
  {meta: M_ProgressiveBlurFocus, Component: C_ProgressiveBlurFocus as React.ComponentType, file: 'grade/progressive-blur-focus/ProgressiveBlurFocus.tsx'},
  {meta: M_GlitchText, Component: C_GlitchText as React.ComponentType, file: 'looks/glitch-text/GlitchText.tsx'},
  {meta: M_HalftonePrint, Component: C_HalftonePrint as React.ComponentType, file: 'looks/halftone-print/HalftonePrint.tsx'},
  {meta: M_MetaballGoo, Component: C_MetaballGoo as React.ComponentType, file: 'looks/metaball-goo/MetaballGoo.tsx'},
  {meta: M_PixelDissolveReveal, Component: C_PixelDissolveReveal as React.ComponentType, file: 'looks/pixel-dissolve-reveal/PixelDissolveReveal.tsx'},
  {meta: M_VhsVintage, Component: C_VhsVintage as React.ComponentType, file: 'looks/vhs-vintage/VhsVintage.tsx'},
  {meta: M_AspectMorphCard, Component: C_AspectMorphCard as React.ComponentType, file: 'motion/aspect-morph-card/AspectMorphCard.tsx'},
  {meta: M_GridToHero, Component: C_GridToHero as React.ComponentType, file: 'motion/grid-to-hero/GridToHero.tsx'},
  {meta: M_OrbitSystem, Component: C_OrbitSystem as React.ComponentType, file: 'motion/orbit-system/OrbitSystem.tsx'},
  {meta: M_ParallaxLayers, Component: C_ParallaxLayers as React.ComponentType, file: 'motion/parallax-layers/ParallaxLayers.tsx'},
  {meta: M_ParticleField, Component: C_ParticleField as React.ComponentType, file: 'motion/particle-field/ParticleField.tsx'},
  {meta: M_EffectsCatalogue, Component: C_EffectsCatalogue as React.ComponentType, file: 'reference/effects-catalogue/EffectsCatalogue.tsx'},
  {meta: M_MaskRevealKit, Component: C_MaskRevealKit as React.ComponentType, file: 'reference/mask-reveal-kit/MaskRevealKit.tsx'},
  {meta: M_TransitionSampler, Component: C_TransitionSampler as React.ComponentType, file: 'reference/transition-sampler/TransitionSampler.tsx'},
  {meta: M_HypeCaptions, Component: C_HypeCaptions as React.ComponentType, file: 'social/hype-captions/HypeCaptions.tsx'},
  {meta: M_ImessageLive, Component: C_ImessageLive as React.ComponentType, file: 'social/imessage-live/ImessageLive.tsx'},
  {meta: M_ImessageThread, Component: C_ImessageThread as React.ComponentType, file: 'social/imessage-thread/ImessageThread.tsx'},
  {meta: M_SubscribeButton, Component: C_SubscribeButton as React.ComponentType, file: 'social/subscribe-button/SubscribeButton.tsx'},
  {meta: M_Audiogram, Component: C_Audiogram as React.ComponentType, file: 'sound/audiogram/Audiogram.tsx'},
  {meta: M_FftBars, Component: C_FftBars as React.ComponentType, file: 'sound/fft-bars/FftBars.tsx'},
  {meta: M_DnaHelix, Component: C_DnaHelix as React.ComponentType, file: 'three-d/dna-helix/DnaHelix.tsx'},
  {meta: M_GalaxyParticles, Component: C_GalaxyParticles as React.ComponentType, file: 'three-d/galaxy-particles/GalaxyParticles.tsx'},
  {meta: M_GlassRefraction, Component: C_GlassRefraction as React.ComponentType, file: 'three-d/glass-refraction/GlassRefraction.tsx'},
  {meta: M_InfiniteTunnel, Component: C_InfiniteTunnel as React.ComponentType, file: 'three-d/infinite-tunnel/InfiniteTunnel.tsx'},
  {meta: M_InstancedCubeWave, Component: C_InstancedCubeWave as React.ComponentType, file: 'three-d/instanced-cube-wave/InstancedCubeWave.tsx'},
  {meta: M_ShaderBlob, Component: C_ShaderBlob as React.ComponentType, file: 'three-d/shader-blob/ShaderBlob.tsx'},
  {meta: M_ThreeRotatingLogo, Component: C_ThreeRotatingLogo as React.ComponentType, file: 'three-d/three-rotating-logo/ThreeRotatingLogo.tsx'},
  {meta: M_ChapterDivider, Component: C_ChapterDivider as React.ComponentType, file: 'titles/chapter-divider/ChapterDivider.tsx'},
  {meta: M_CinematicTechIntro, Component: C_CinematicTechIntro as React.ComponentType, file: 'titles/cinematic-tech-intro/CinematicTechIntro.tsx'},
  {meta: M_CountdownLeader, Component: C_CountdownLeader as React.ComponentType, file: 'titles/countdown-leader/CountdownLeader.tsx'},
  {meta: M_LowerThird, Component: C_LowerThird as React.ComponentType, file: 'titles/lower-third/LowerThird.tsx'},
  {meta: M_QuoteSlam, Component: C_QuoteSlam as React.ComponentType, file: 'titles/quote-slam/QuoteSlam.tsx'},
  {meta: M_StatSlam, Component: C_StatSlam as React.ComponentType, file: 'titles/stat-slam/StatSlam.tsx'},
  {meta: M_CssCardFlip, Component: C_CssCardFlip as React.ComponentType, file: 'transitions/css-card-flip/CssCardFlip.tsx'},
  {meta: M_CustomCircleReveal, Component: C_CustomCircleReveal as React.ComponentType, file: 'transitions/custom-circle-reveal/CustomCircleReveal.tsx'},
  {meta: M_LightLeakTransition, Component: C_LightLeakTransition as React.ComponentType, file: 'transitions/light-leak-transition/LightLeakTransition.tsx'},
  {meta: M_VoronoiShatter, Component: C_VoronoiShatter as React.ComponentType, file: 'transitions/voronoi-shatter/VoronoiShatter.tsx'},
  {meta: M_WhipPan, Component: C_WhipPan as React.ComponentType, file: 'transitions/whip-pan/WhipPan.tsx'},
  {meta: M_CharDropSpring, Component: C_CharDropSpring as React.ComponentType, file: 'type/char-drop-spring/CharDropSpring.tsx'},
  {meta: M_ExtrudedText, Component: C_ExtrudedText as React.ComponentType, file: 'type/extruded-text/ExtrudedText.tsx'},
  {meta: M_GradientTextSweep, Component: C_GradientTextSweep as React.ComponentType, file: 'type/gradient-text-sweep/GradientTextSweep.tsx'},
  {meta: M_HeadlineHighlight, Component: C_HeadlineHighlight as React.ComponentType, file: 'type/headline-highlight/HeadlineHighlight.tsx'},
  {meta: M_KineticWordReveal, Component: C_KineticWordReveal as React.ComponentType, file: 'type/kinetic-word-reveal/KineticWordReveal.tsx'},
  {meta: M_SplitFlapBoard, Component: C_SplitFlapBoard as React.ComponentType, file: 'type/split-flap-board/SplitFlapBoard.tsx'},
  {meta: M_TextBehindSubject, Component: C_TextBehindSubject as React.ComponentType, file: 'type/text-behind-subject/TextBehindSubject.tsx'},
  {meta: M_TextMaskReveal, Component: C_TextMaskReveal as React.ComponentType, file: 'type/text-mask-reveal/TextMaskReveal.tsx'},
  {meta: M_TextScramble, Component: C_TextScramble as React.ComponentType, file: 'type/text-scramble/TextScramble.tsx'},
  {meta: M_TypewriterTerminal, Component: C_TypewriterTerminal as React.ComponentType, file: 'type/typewriter-terminal/TypewriterTerminal.tsx'},
  {meta: M_VideoInText, Component: C_VideoInText as React.ComponentType, file: 'type/video-in-text/VideoInText.tsx'},
  {meta: M_BrowserWindowScroll, Component: C_BrowserWindowScroll as React.ComponentType, file: 'ui/browser-window-scroll/BrowserWindowScroll.tsx'},
  {meta: M_ChatgptFullUi, Component: C_ChatgptFullUi as React.ComponentType, file: 'ui/chatgpt-full-ui/ChatgptFullUi.tsx'},
  {meta: M_ClaudeFullUi, Component: C_ClaudeFullUi as React.ComponentType, file: 'ui/claude-full-ui/ClaudeFullUi.tsx'},
  {meta: M_CodeEditorTyping, Component: C_CodeEditorTyping as React.ComponentType, file: 'ui/code-editor-typing/CodeEditorTyping.tsx'},
  {meta: M_DeviceRise, Component: C_DeviceRise as React.ComponentType, file: 'ui/device-rise/DeviceRise.tsx'},
  {meta: M_HeroHandoverUi, Component: C_HeroHandoverUi as React.ComponentType, file: 'ui/hero-handover-ui/HeroHandoverUi.tsx'},
  {meta: M_NotificationStack, Component: C_NotificationStack as React.ComponentType, file: 'ui/notification-stack/NotificationStack.tsx'},
];

/**
 * Base entries plus one per `meta.variants` entry.
 *
 * Expansion happens here, at runtime, rather than in the codegen: the variant
 * list already lives in a typed `meta.ts` the compiler checks, and duplicating
 * it into generated source would give it a second place to be wrong. A variant
 * inherits everything from its parent except the four fields it may override,
 * and carries `parentId` so the gallery can group a family and the prompt can
 * point at one brief rather than eighty-three.
 */
export const effects: readonly EffectEntry[] = base.flatMap((e) =>
  e.meta.variants && e.meta.variants.length > 0
    ? [
        e,
        ...e.meta.variants.map(
          (v): EffectEntry => ({
            meta: {
              ...e.meta,
              id: `${e.meta.id}--${v.id}`,
              name: v.name,
              tagline: v.tagline ?? e.meta.tagline,
              checkFrame: v.checkFrame ?? e.meta.checkFrame,
              posterFrame: v.posterFrame ?? e.meta.posterFrame,
              // A variant is a leaf; leaving the list on it would recurse.
              variants: undefined,
            },
            Component: e.Component,
            file: e.file,
            parentId: e.meta.id,
            variantProps: v.props,
          }),
        ),
      ]
    : [e],
);

/** Entries that are variants of something else, by parent id. */
export const variantsOf = (id: string) => effects.filter((e) => e.parentId === id);

export const effectById = (id: string) => effects.find((e) => e.meta.id === id);

/**
 * Everything in public/. staticFile() returns a ROOT-absolute path with no way
 * to prefix a base, so a gallery served from a subpath (GitHub Pages project
 * sites, for instance) has to remap these before the app mounts. See
 * src/gallery/main.tsx.
 */
export const publicAssets: readonly string[] = [
  'ASSETS.md',
  'audio/music-bed.mp3',
  'audio/sfx/chime.mp3',
  'audio/sfx/click.mp3',
  'audio/sfx/impact.mp3',
  'audio/sfx/key.mp3',
  'audio/sfx/pop.mp3',
  'audio/sfx/riser.mp3',
  'audio/sfx/shutter.mp3',
  'audio/sfx/sub-drop.mp3',
  'audio/sfx/swish.mp3',
  'audio/sfx/whoosh.mp3',
  'footage/broll-earth.mp4',
  'footage/broll-eva.mp4',
  'footage/broll-night.mp4',
  'footage/broll-sunrise.mp4',
  'footage/interview-raw.mp4',
  'footage/interview.mp4',
  'plate-1.svg',
  'plate-2.svg',
  'plate-3.svg',
  'plate-4.svg',
  'plate-5.svg',
  'sample-city.svg',
  'sample-scene.svg',
  'subject-skyline.svg',
  'transcripts/interview-raw.deepgram.json',
  'transcripts/interview.deepgram.json',
];
